### ISSUE TITLE
[Bug] Fullscreen break doesn't seem to trigger when there is another app opened in fullscreen

### ISSUE THREAD

**Issue by isle99** [tom-james-watson/breaktimer-app#104]

**Comment by tom-james-watson** [comment]
What platform?

**Comment by isle99** [comment]
This is on Windows.

**Comment by isle99** [comment]
I'll try to replicate the bug soonish, and I'll get back to you.

**Comment by soredake** [comment]
Would be nice to have option to skip breaks when some fullscreen program is active

**Comment by tom-james-watson** [comment]
This is the intended functionality at the moment. We wouldn't want the app to take over when there's a fullscreen app like a game open.
