### ISSUE TITLE
[Feature request] Long break

### ISSUE THREAD

**Issue by isle99** [tom-james-watson/breaktimer-app#105]

**Comment by tom-james-watson** [comment]
You'll need to provide a description of what you mean.

**Comment by tom-james-watson** [comment]
Potentially a duplicate of https://github.com/tom-james-watson/breaktimer-app/issues/77.

**Comment by isle99** [comment]
This would be similar to what a lot of pomodoro apps use. After X short breaks a long break is triggered with a different length.

This definitely could be integrated with issue #77. It's probably a much better idea to just let users decide what breaks they want.

**Comment by tom-james-watson** [comment]
OK - closing as a duplicate of https://github.com/tom-james-watson/breaktimer-app/issues/77 then. Feel free to comment there if you don't feel like your request is represented by the current description.
