### ISSUE TITLE
Notification is easy to miss

### ISSUE THREAD

**Issue by holden321** [tom-james-watson/breaktimer-app#106]
I think it should hang until it clicked.

**Comment by tom-james-watson** [comment]
This is not something we can control - the length of time the notification stays visible is controlled by each operating system.

**Comment by holden321** [comment]
Then the system notification is a wrong thing to use for a break timer app.
Maybe it makes sense to consider using own notification windows.
Just a small topmost window near the clock.
I switched to Big Stretch Reminder for a while.
At least it shows a popup window at the center of the screen to notify.
