### ISSUE TITLE
Idle reset reportedly not working on Windows

### ISSUE THREAD

**Issue by tom-james-watson** [tom-james-watson/breaktimer-app#11]
A user contacted me via email to report a bug where idle reset allegedly just straight up does not work.

Will need to get round to investigating (Windows is the OS I use least).

**Comment by tom-james-watson** [comment]
I can confirm the feature is working as expected on Ubuntu.

**Comment by Satyrars** [comment]
Hey, decided it's time to join the community :) I'll share my original message to you - tell me if you need any additional details.

---

BreakTimer doesn't seem to respect the Idle Reset setting. It wasn't working while it was a chrome extension, and it doesn't work now as a Windows app. The Breaks are still occurring even if I'm away from computer, I hear dings during my working hours. Also just explicitly tested it for the same result.
![image](https://user-images.githubusercontent.com/9111191/68302554-f7335c00-00aa-11ea-829a-1921053a611d.png)

Version 0.5.0
Windows 10

**Comment by Satyrars** [comment]
Also, can you share how it checks if the user is idle? Maybe it can help figure it out.

**Comment by tom-james-watson** [comment]
The relevant code is here - https://github.com/tom-james-watson/breaktimer-app/blob/master/app/main/lib/breaks.ts#L173-L184

It's using this electron lib - https://electronjs.org/docs/api/power-monitor#powermonitorgetsystemidlestateidlethreshold

**Comment by Satyrars** [comment]
The documentation is kinda vague on what is considered "idle time", but if it measures the powerstate, I guess it won't register the idle time if some processes are actively running? 

Is it possible to implement the idle checkup based on mouse movement & key presses? This way it will check if you're actually working on the computer or it's just running in the background.

**Comment by tom-james-watson** [comment]
I'm 99% sure it is based on mouse movement and key presses. That's what it detects when I test it. I will get round to trying it with some other windows machines soon.

**Comment by tom-james-watson** [comment]
As of version `0.6.0`, which has just been released, you now receive a notification whenever the break is reset due to idle reset. The notification will also tell you how long you were deemed to have been idle.

Hopefully this should make it more obvious whether this feature is working or not and should help with debugging.

Why don't you give it a go and let me know if you ever see any idle reset notifications @Satyrars ?
