### ISSUE TITLE
Broken settings dialog in 1.0.0

### ISSUE THREAD

**Issue by WayneKoorts** [tom-james-watson/breaktimer-app#112]
Hello, I've just upgraded to v1.0.0 and the app seems to be functioning correctly other than the fact that the settings dialog is blank.  It opens and has the "BreakTimer" title, but is just plain white.

**Comment by tom-james-watson** [comment]
Hmm that's strange. Could you please upload yours logs (https://github.com/tom-james-watson/breaktimer-app#how-can-i-pass-you-my-log-files-to-help-you-debug-an-issue) to a gist (https://gist.github.com/)?

Hopefully this is an isolated case. If anyone else sees this, please add a comment or a thumbs up reaction to the top comment.

To try and actually fix the issue, https://github.com/tom-james-watson/breaktimer-app#how-can-i-hard-reset-the-apps-data should work.
