### ISSUE TITLE
Notification UI duplicated

### ISSUE THREAD

**Issue by Perturbatio** [tom-james-watson/breaktimer-app#114]
When I receive a notification to take a break (and when the break starts), the UI is duplicated and offset slightly.

![image](https://user-images.githubusercontent.com/1007702/136223808-43e3eb2f-8574-4d14-b793-a5502347a4e2.png)

Linux Mint 20.2 (Uma) using cinnamon.

**Comment by tom-james-watson** [comment]
I assume one of the monitors didn't have a popup at all? There should be one popup on each monitor.

**Comment by stephenjamieson** [comment]
I have this issue with 2 monitors and the built in monitor.
