### ISSUE TITLE
Break behavior 1.0.0

### ISSUE THREAD

**Issue by rscrane49** [tom-james-watson/breaktimer-app#117]
Without true full screen option, there's not really an enforced break -- I found can ! work around the notification circle.  I don't have the willpower and would like a option to force a real break.

**Comment by tom-james-watson** [comment]
I think allowing for slightly different shapes and sizes of the break window could potentially be a reasonable aporoach. There are reasons why the way the old one doesn't work great in some circumstances, but it should be fairly easy to support a break window that occupies the vast majority of the screen, for example.

**Comment by rscrane49** [comment]
That should work.  I do want to emphasize how much I appreciate the app, and find it extremely useful and easy to use.
