### ISSUE TITLE
The circular break screen introduced in 1.0 is barely visible

### ISSUE THREAD

**Issue by iirekm** [tom-james-watson/breaktimer-app#118]
- On 2-monitor setup (laptop + big monitor) it's visible only on laptop's small screen 
- Even on laptop's screen it's too small and very easy to miss

Workaround: downgrade to a pre-1.0 version with full screen break screen

**Comment by CodeNinja1337** [comment]
I like the circle but as you mention, its only on visible on my laptop screen so i miss it half of the time.
A nice solution would be to make it configurable on wich screen the circle pops up (this may be complex as the amount of screen can differ depending on the usage of the laptop) or add the option "Full screen" to "Notify me with"

**Comment by tom-james-watson** [comment]
That it only shows on your laptop screen is a workaround for a windows bug that renders the notification window strangely. On macOS and Linux it does display on all screens. Hopefully that can actually be fixed.

**Comment by tom-james-watson** [comment]
With BreakTimer 1.1.0, a new setting has been introduced which should resolve this. If you open the settings and go to Customization, turn on "Show backdrop" to turn on a fullscreen backdrop on breaks. You can play with the color and opacity to achieve the look you want. If you set the same color for the backdrop as the primary color and set the backdrop opacity to 1, you will effectively get back the fullscreen break.
