### ISSUE TITLE
Snap version displays severe graphical glitching

### ISSUE THREAD

**Issue by AreoByte** [tom-james-watson/breaktimer-app#120]
**Describe the bug**
Certain elements of the BreakTimer Snap displays severe graphical artifacts on the UI. The AppImage version does not have this issue.

**To Reproduce**
1. Run `sudo snap install breaktimer` on Solus (4.3 Fortitude) to install BreakTimer
2. Run BreakTimer (either through desktop or terminal)
3. Go to settings and click on "Popup break" and see graphical glitching (optional)
4. Click the BreakTimer icon and select "Start break now" to see graphical glitching

**Expected behavior**
I was expecting no graphical artifacts and for the application to work as intended.

**Screenshots**
Snap version not working as intended:
![glitching](https://user-images.githubusercontent.com/84479813/139599991-01d3c301-f6ec-48d4-b59f-231d7f1d07a0.png)
![Screenshot from 2021-10-31 15-07-10](https://user-images.githubusercontent.com/84479813/139600618-96f6a700-4c64-4076-b7ab-a5c315f16f0a.png)

**Specs:**

```
lost@oxygen 
----------- 
OS: Solus x86_64 
Kernel: 5.14.15-203.current 
Uptime: 1 hour, 14 mins 
Packages: 775 (eopkg), 5 (flatpak), 9 (snap) 
Shell: bash 5.1.8 
Resolution: 1920x1080 
DE: Budgie (git-26cde8fd300a87aba0d085ca50c89728150138d2 
WM: Mutter(Budgie) 
Theme: Plata-Noir [GTK2/3] 
Icons: Papirus [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 5 2400G (8) @ 3.600GHz 
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
Memory: 2576MiB / 13920MiB 
```

**Additional context**
When I compared the terminal output between the Snap version and the AppImage version, I noticed that there were was one extra error from the Snap version:

```
[3983:1031/150643.048831:ERROR:browser_main_loop.cc(269)] Gdk: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```

I am also using integrated AMD graphics.

Here are the full terminal logs for the two versions of BreakTimer:
[Snap log](https://gist.github.com/AreoByte/592632298ea6cfcdcff57c1bb1402afd)
[AppImage log](https://gist.github.com/AreoByte/340a8f7c38645cc7ecc5fd518177fd9b)

**Comment by AreoByte** [comment]
This seems to be an issue on my side since Spotify also has artifacts. From the very sparse information I can find, it seems like my distro. doesn't like the APU I have.

**Comment by tom-james-watson** [comment]
Thanks for the info!

**Comment by RafaelWO** [comment]
@tom-james-watson I'm experiencing a similar issue:

![image](https://user-images.githubusercontent.com/38643099/155483691-76243427-d1f0-4009-8759-43ece7a7e9c1.png)

My specs:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
Kernel:         5.13.0-30-generic
```

Any ideas regarding a fix?
