### ISSUE TITLE
Gong sound plays even when turned off in settings

### ISSUE THREAD

**Issue by ryankingart** [tom-james-watson/breaktimer-app#122]
I do not want the gong sound on break start/end. So I turned it off in the settings, and saved the settings. But it still plays the gong sound. This seems to be a bug to me. I an using the .Deb version of the program. I tried re-installing it, but the problem remains.

**My OS:**
Linux Mint 19.3 Cinnamon

**Comment by samsong** [comment]
Confirm the same on Windows 10

**Comment by ryankingart** [comment]
> Confirm the same on Windows 10

Sorry, but I'm not able to do that. I don't have any computer with Windows 10. I don't use windows. I switched to using an older version of Break timer, and the bug isn't there on the older version. So I'm ok with just using the older version for now.
Thanks,

**Comment by tom-james-watson** [comment]
I think they're just saying that they all see the same on Windows 10.

This is definitely a bug, so reopening. I've confirmed it too.

**Comment by ryankingart** [comment]
> I think they're just saying that they all see the same on Windows 10.
> 
> This is definitely a bug, so reopening. I've confirmed it too.

Ok, Thank you!

**Comment by tom-james-watson** [comment]
This has been fixed in 1.0.1, which has just been released :slightly_smiling_face:

**Comment by ryankingart** [comment]
> This has been fixed in 1.0.1, which has just been released slightly_smiling_face

Ok cool! Thank you so much!
