### ISSUE TITLE
1.0.1: Javascript error

### ISSUE THREAD

**Issue by samsong** [tom-james-watson/breaktimer-app#125]
windows 10
new version 1.0.1

"cannot read properties of undefined (reading "hide")"
[(https://i.ibb.co/2306py1/break.jpg)]

**Comment by samsong** [comment]
[https://i.ibb.co/2306py1/break.jpg](https://i.ibb.co/2306py1/break.jpg)

**Comment by tom-james-watson** [comment]
Yeah can confirm. I'm going to deploy a 1.0.2 hotfix now.
