### ISSUE TITLE
Allow for multiple working hour ranges per day

### ISSUE THREAD

**Issue by richardlin047** [tom-james-watson/breaktimer-app#128]
If I have working hours 9am-6pm, but don't want breaks at 1-2pm. Same effect as having multiple working hour periods, but maybe easier to reason about.

**Comment by kitserve** [comment]
I would also find this helpful. I often forget to disable BreakTimer before meetings, which causes some problems. For my regular scheduled meetings, if I could set them as non-working hours, it would save me having to remember to disable BreakTimer.

**Comment by iamfilipp** [comment]
+1 from me 🙏🏻

**Comment by tom-james-watson** [comment]
As of 1.3.0 you can have multiple ranges per day :)
