### ISSUE TITLE
Explore adding optional backdrop on popup break to obscure screen contents

### ISSUE THREAD

**Issue by kitserve** [tom-james-watson/breaktimer-app#129]
Since upgrading to version 1, I can only see the options for "Popup break" or "Simple notification". Please restore the option for a fullscreen break. I just don't have the self discipline to stop what I'm doing half the time when I can still see it on the screen!

If possible, it would also be nice if you could disable the Ctrl+W shortcut that closes the fullscreen popover. I discovered it by accident (I frequently use it in other apps) but now I know it's there, the temptation to use it when I'm in the middle of something is sometimes too strong. Making the app totally unclosable is undoubtedly hard and I'm not suggesting that it would be a good idea to implement even if possible, but currently I think it's just a bit too easy.

One other thing I noticed: after upgrading, the timings change to something really strange. This could be a quirk of my setup, but it seems that the timers were changed to 20+ hours. I'm using the .deb version on Ubuntu 21.10 (although have been using BreakTimer for a year or two through OS version upgrades).

**Comment by kitserve** [comment]
Just to add, I've read the rationale about the change away from the fullscreen mode, and I prefer the circular timer to the text, but I'd personally prefer to still have the option for a fullscreen break. I've deliberately turned off the options to postpone or skip breaks, because the temptation to use them would be too great.

**Comment by tom-james-watson** [comment]
I will not be bringing back the old fullscreen option, but obviously we can think about ways to improve the new popup break.

I think for your use case having the option to have a translucent/opaque backdrop that obscures the rest of your screen would work, for example.

Did you by any chance change to a different timezone (eg travelling) when you saw the time bug?

**Comment by kitserve** [comment]
Fair enough. From my perspective, the popup doesn't need to be full screen, but it does need to obscure much more of the desktop, and prevent interaction with it.

You're correct, I quite frequently change timezones, it's entirely possible that I misremembered and the time bug coincided with timezone changes rather than upgrades.

**Comment by sanidhya-saraswat2** [comment]
@tom-james-watson, I can work on the development of the optional/mandatory backdrop feature, if you want to add this feature to the app. Please let me know.

**Comment by tom-james-watson** [comment]
Yeah, of course, contributions are always welcome! 🙂

**Comment by sanidhya-saraswat** [comment]
@tom-james-watson , have a look: https://github.com/tom-james-watson/breaktimer-app/pull/137
