### ISSUE TITLE
Notifications on MacOS don't respect system settings for alert style

### ISSUE THREAD

**Issue by krzdabrowski** [tom-james-watson/breaktimer-app#132]
**Describe the bug**
I don't know if it's a kind of duplicate of [this issue](https://github.com/tom-james-watson/breaktimer-app/issues/106) but on MacOS app notifications go away automatically. This is a proper behaviour for "Banners" setting in Notifications & Focus system settings but as Apple says, there's also an another option called "Alerts". Quoting: "Alerts stay on screen until dismissed".
Choosing this option does nothing, it still behaves like a Banner setting.

**To Reproduce**
1. Choose "Notify me with" to "Simple notification" in app settings.
2. Go to System settings, Notifications & Focus, choose BreakTimer
3. Choose BreakTimer alert type to Alerts
4. Wait for next break
4. Notification is a banner, not an alert

**Expected behavior**
I can set the notification behaviour in system settings and it's respected by the app. 

**Screenshots**
For reference, here's the menu I'm talking about:
![MacOS settings](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/macos/Catalina/macos-catalina-system-prefs-notifications-calendar-alerts.jpg)

**Specs:**
 - OS version: MacOS Monterey, Apple Silicon chipset (if it matters)

**Comment by sanidhya-saraswat** [comment]
@tom-james-watson have a look: https://github.com/tom-james-watson/breaktimer-app/pull/141

**Comment by tom-james-watson** [comment]
This requires some more thought I think. This was deliberate on my part because my thought was that once the time for the break has passed, it's no longer really relevant. I personally wouldn't want the notification to stick around. I'd need to check what the behaviour defaults to on macOS.

**Comment by sanidhya-saraswat** [comment]
For MacOS,
As I said in the PR, when notification style is **Banner**, notifications appear and go away automatically without the need of `forceClose` flag (tested by me).  But if the user explicitly chooses notification style as **Alerts**, then we wants the notification to stick around.

**Comment by tom-james-watson** [comment]
Closed by https://github.com/tom-james-watson/breaktimer-app/pull/141. Thanks @sanidhya-saraswat !

**Comment by tom-james-watson** [comment]
Released in BreakTimer 1.1.0

**Comment by krzdabrowski** [comment]
I confirm it works, thanks guys 👍
