### ISSUE TITLE
Linux AppImage starting at login not working 

### ISSUE THREAD

**Issue by FinnZhang** [tom-james-watson/breaktimer-app#133]
**Describe the bug**
Linux AppImage starting at login not working 

**To Reproduce**
1. Enable start login in settings
2. Reboot OS
3. Not start at login

**Expected behavior**
Should start at login

**Specs:**
 - OS version: Linux Mint 20.2

**Additional context**
The issue is the config error in file  `~/.config/autostart/breaktimer.desktop` 
The Exec value should be the AppImage file path instead of /mnt/.moutxxx Path.

**Comment by tom-james-watson** [comment]
Closed by https://github.com/tom-james-watson/breaktimer-app/pull/135#issuecomment-1008361175
