### ISSUE TITLE
[enhancement] Add a break countdown timer to the Windows 10 version.

### ISSUE THREAD

**Issue by DMunkei** [tom-james-watson/breaktimer-app#138]
Would be nice to see a countdown showing how long is left until the break is over.  Just like in the screenshots and keeping it still circular.
Combining both, if possible? 
Countdown timer            |  Circular design
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/17084284/148690895-a3deb693-371a-4b20-b788-c4c0c275d90d.png)  |  ![image](https://user-images.githubusercontent.com/17084284/148691066-672d194d-b159-4773-a499-113b802d391d.png)

**Comment by tom-james-watson** [comment]
You've just reminded me to update those screenshots 😆 !  That's the old design. At this point I don't plan on bringing the clock-style countdown back, unless I receive a lot of demand to anyway.

**Comment by DMunkei** [comment]
Ah, alright. ^^
