### ISSUE TITLE
[bug] Windows 10 "Start break now" from system tray doesn't work

### ISSUE THREAD

**Issue by DMunkei** [tom-james-watson/breaktimer-app#139]
**Describe the bug**
Selecting "Start break now" from the system tray doesn't start the break. "Next break in less than a minute" is written when checking the system tray again and nothing actually triggers.

**To Reproduce**
1. Right click on icon in system tray
2. click start break now
**Expected behavior**
Break should start

**Screenshots**
![image](https://user-images.githubusercontent.com/17084284/148691575-dede639f-a36c-4a38-94c0-b805bcb12310.png)

**Specs:**
-Windows 10

**Additional context**
Quitting and restarting fixes the bug.
Disabling and Enabling the app doesn't fix it.
Notify me with set to Popup break
Break frequency set to 50min
Break length set to 10 min
Idle reset activate set to 5 min
Primary and Text colour changed from default values.

**Comment by TheMetaWolfe** [comment]
This bug is happening to me too, and with the nearly exact same specs. The only small difference is the break frequency is 1 hour.

**Comment by sanidhya-saraswat2** [comment]
Same here on MacOS.

**Comment by kamal-choudhary** [comment]
facing same issue on macOS.

**Comment by tom-james-watson** [comment]
This looks like the real problem is https://github.com/tom-james-watson/breaktimer-app/issues/206
