### ISSUE TITLE
No Break Notification

### ISSUE THREAD

**Issue by Haggagz** [tom-james-watson/breaktimer-app#14]
The break timer ends (30 mins) and then restarts itself without any further notification, when I modify it to 1 min break, it's fixed!

**Comment by tom-james-watson** [comment]
Can you try setting it back to what it was set to before? How consistently does this happen. What if you press the tray icon and select "Start break now"?

Do you have "Notify me with" set to "Fullscreen popup" or "Simple notification"? The fullscreen popup is a little slow to open depending on your system - this is something I'm looking to improve.

**Comment by Haggagz** [comment]
I'll try setting it back to 28mins, this always happens. Didn't try "Start break now". I have fullscreen popup.

**Comment by Haggagz** [comment]
The problem is still up Tom, and it's very annoying

**Comment by tom-james-watson** [comment]
Can you try "Start break now"? What platform are you? Can you also click on About in the tray icon and check that you are on version `0.5.0`?

**Comment by Haggagz** [comment]
Start break now does start the break, I'm on Ubuntu 16.04 LTS, version is 0.5.0.

The problem is still up.

**Comment by tom-james-watson** [comment]
Going to close this out as I haven't seen this problem with anyone else and you are running a pretty old ubuntu version. I'd say the minimum version would be 18.04.
