### ISSUE TITLE
[Enhancement] Option to show remaining time with the tray icon.

### ISSUE THREAD

**Issue by sanidhya-saraswat** [tom-james-watson/breaktimer-app#142]
**Enhancement Request**
Option to show remaining time with the tray icon. Something like this:   <img width="59" alt="Screenshot 2022-01-12 at 12 24 32 PM" src="https://user-images.githubusercontent.com/21276981/149078714-ff817ae0-f254-4db1-95b4-95b74594f6b6.png">

It will be optional (controlled via settings)
I can work on it if you agree with the same.

**Comment by tom-james-watson** [comment]
Some work was already started on implementing this by having a dynamic icon, as opposed to showing the number of minutes left. I think a dynamic icon is a better way of doing it. You can see the assets that were provided here - https://github.com/tom-james-watson/breaktimer-app/pull/108. If you wanted to take that PR and actually implement the dynamic icon, that would be awesome. There is some complexity around icons on macOS where they need to be monochrome, which you would need to look into.

**Comment by sanidhya-saraswat** [comment]
yup, I agree. The issue is with MacOS, those colorful icons wont work.
