### ISSUE TITLE
Sometimes breaks do not appear.  

### ISSUE THREAD

**Issue by sanidhya-saraswat2** [tom-james-watson/breaktimer-app#143]
**Describe the bug**

Sometimes breaks do not appear.  Its stuck at **Less than a minute**. Even when clicking **Start break now** nothing happens. Restarting the breakTimer app fixes the issue.

**Specs:**
 - OS version: macOS 11.6.1

**Additional context**
Happens randomly. I checked the main.log file. Nothing unusual. No error.

**Comment by sanidhya-saraswat2** [comment]
I will try to get more info. Adding more logs (info and error) in the application may help

**Comment by tom-james-watson** [comment]
I think this is related to https://github.com/tom-james-watson/breaktimer-app/issues/139.

**Comment by sanidhya-saraswat2** [comment]
True. This can be marked as duplicate.

**Comment by tom-james-watson** [comment]
I'll close this out. If you could recreate it in dev and work out what is going wrong that would be amazing!

**Comment by tom-james-watson** [comment]
I have limited time to look at this myself at the moment :confused:
