### ISSUE TITLE
Alert window sometimes doesn't appear on top

### ISSUE THREAD

**Issue by abutaleb1** [tom-james-watson/breaktimer-app#146]
The app works the first few times and appears on top of all other apps. However, lately, the alert window appears behind all other apps. I have the latest version 1.0.3.

**Comment by emaadgh** [comment]
I have the exact same problem!

While I can hear the beep sound effect for rest time, the full-screen alert does not appear in front. I discovered that BreakTimer's full-screen alert is hidden behind open applications. 

I'm using BreakTimer version 1.2 and Windows 10 Home 21H2.
