### ISSUE TITLE
Doesn't start on Ubuntu 20.04 LTS (snap)

### ISSUE THREAD

**Issue by MFykoopS** [tom-james-watson/breaktimer-app#147]
**Describe the bug**
I have installed the app via snap, but it doesn't start, neither via the shortcut nor via the command line. There is no error message. I am using Ubuntu 20.04 LTS.

**To Reproduce**
1. Open Terminal.
2. `sudo snap install breaktimer`
3. Installs without error
4. `breaktimer` --> nothing happens
5. Open menu (Super-Key) --> click on Breaktimer icon --> nothing happens

**Expected behavior**
App should start.

**Specs:**
Ubuntu 20.04
installed version is 1.1.0

**Comment by MFykoopS** [comment]
This is maybe my second issue I open on GitHub so please let me know if I left anything out, did something wrong or should include anything else (log files etc.).

**Comment by LukasGibeh** [comment]
Hi @MFykoopS 

I just experienced a similar issue.

When I install `breaktimer` (version 1.1.0, rev 37) via `snap install breaktimer` on my system (Ubuntu 20.04.4 LTS via snap), it runs successfully for the first time (i.e. the tray icon appears and the app is running, when quitting the app via the tray icon, the exit code (`echo $?`) is `0`).

However, when I try to start it a second time, the app exits immediately without any message in the log file (`~/snap/breaktimer/37/.config/BreakTimer/logs/main.log`):
```
[2022-05-25 11:01:40.914] [info]  Checking for updates...
[2022-05-25 11:01:40.924] [info]  SNAP env is defined, updater is disabled
```
The message is above is from the first start, the subsequent (unsuccessful) starts yield no log messages.

It seems, that `rm snap/breaktimer/37/.config/user-dirs.dirs` is solving this problem. After I issued the command, I can start `breaktimer` without problems.

Best regards,
LukasGibeh

**Comment by blinard-BIOINFO** [comment]
@tom-james-watson 
Hi, 
This issue is still present in Ubuntu 22.04, using the last `breaktimer 1.2.0` and `sudo snap install breaktimer`.

* After initial snap installation, breaktimer runs smoothly
* After a reboot, it cannot be launched anymore
* Nothing is logged in `~/snap/breaktimer/39/.config/BreakTimer/logs/main.log`
* Manually deleting `~/snap/breaktimer/39/.config/user-dirs.dirs`before launch allows to run breaktimer

**Comment by tom-james-watson** [comment]
Closing this due to age. If this is a still a problem, let me know. It seems to work fine for me on latest Ubuntu LTS.
