### ISSUE TITLE
[Feature request]: Allow running multiple timers and have labelled breaks

### ISSUE THREAD

**Issue by Infi-Knight** [tom-james-watson/breaktimer-app#152]
Thank you for making this lovely app. I found breaktimer while looking for [Safe Eyes](https://slgobinath.github.io/SafeEyes/) alternative. It would be nice to have some of it's features like:

- Ability to add short and long breaks
- Cycle between labelled breaks e.g short break to rotate your eyes, then move on to a break for closing your eyes etc

**Comment by sepehrg** [comment]
I'm in agree with Infi-Knight. Short breaks are really missing in this application. Could anyone add it?

**Comment by sepehrg** [comment]
For anyone who looks for this feature, you can clone the code and package and install it as I did. Then you'll have a duplicate application that you can set another break interval on it.

**Comment by tom-james-watson** [comment]
I don't think this is something I intend on supporting. I gave some thought to how breaks worked recently and considered supporting things like this or pomodoro-style breaks, but I decided that I'd prefer to keep the simplicity of how it currently works. Trying to do anything different is a rabbit hole of conflicting opinions and getting something that would please everyone would be impossible.
