### ISSUE TITLE
Notification sound prior to going to break [enhancement]

### ISSUE THREAD

**Issue by philiprenich** [tom-james-watson/breaktimer-app#153]
This is a feature request.

I'm not sure if it is possible, but I would find it very useful to have a ding or the BreakTimer gong happen when the notification message pops up in the OS, as opposed (or in addition) to the one that happens once the screens are switched.

In a multi-monitor setup, or with big screens, it is easy to miss the little alert slide in. Having a noise would allow me a better chance to get ready for the break, or to cancel it (if I'm on a call, I don't want to take a break!)

Thanks!

**Comment by tom-james-watson** [comment]
I assume you are on windows. This isn't an issue if https://github.com/tom-james-watson/breaktimer-app/issues/136 is fixed, so I'm going to close this out.

**Comment by philiprenich** [comment]
Oops, that was poor form to  not leave my details: I'm on MacOS 12.3 Monterey.
My setup is that MacOS gives me a notification a few seconds prior to going in to full-screen break mode across all monitors. But that notification is only shown on one screen, and is small, so is easily missed if I want to click to cancel. Hence having the audio notification play before going in to break mode when the notification is displayed would be helpful.
