### ISSUE TITLE
Resizable windows in windows

### ISSUE THREAD

**Issue by master-puller** [tom-james-watson/breaktimer-app#160]
**Describe the bug**
The break timer, when triggered, can be resized to a really small size as to circumvent the timer

**To Reproduce**
1. Setup timer
2. Wait until triggers
3. Move mouse up to top corner
4. Drag down away from corner.

**Expected behavior**
The popup window should stay firmly in place, and should not be resizable.

**Screenshots**
![image](https://user-images.githubusercontent.com/19511301/161444367-7c1f4ec7-8e57-407f-88ac-6da5500f9c48.png)

**Specs:**
 - Windows 10 (10.19042

**Comment by tom-james-watson** [comment]
Thank you for your bug report. I've fixed this in this branch, which should go out soon: https://github.com/tom-james-watson/breaktimer-app/pull/170.
