### ISSUE TITLE
Latest v1.1.0 does not support multi-monitors on windows?

### ISSUE THREAD

**Issue by balajikris** [tom-james-watson/breaktimer-app#165]
**Describe the bug**
I notice that the latest v1.1.0 for windows no longer shows the full-screen backdrop for the secondary monitor. In v0.9.0 this used to work. I see the the pop-up and backdrop were rewritten for v1.0, so hoping this is a small bug that can be easily fixed? 

**Specs:**
 - OS version: win11

**Comment by densha** [comment]
I'm noticing this as well on Windows 11. For me, the pop-up and backdrop only appear on my secondary monitor (as set in display settings). Nice to have would be to customize which monitor it appears or have it appear on both monitors.

**Comment by balajikris** [comment]
I just noticed that this is a duplicate of #136
