### ISSUE TITLE
feature request: end of day reminder

### ISSUE THREAD

**Issue by droundy** [tom-james-watson/breaktimer-app#166]
I'd love to have you track my non-idle time and give me a reminder when the total reaches 8 hours (which should be configurable). Is there a chance you'd be interested in a pull request if I figured this out?

My use case is that I usually work before my family is awake and then after my daughter's gone to preschool. The point of starting in the wee hours is to give my more time for family/home activities in the afternoon, but it's hard to recognize when I've worked enough.

**Comment by tom-james-watson** [comment]
I don't think this is something I would consider adding to be honest. I'd prefer to keep things tight and focused.
