### ISSUE TITLE
[MacOS Catalina 10.15.7] Can't get into full screen

### ISSUE THREAD

**Issue by joja19** [tom-james-watson/breaktimer-app#169]
Hi and thanks for the great app, I'm using it since v 0.9.

Just updated to v 1.1.0, and the popup alert, which is supposedly full screen, does not fill the screen. Instead I get the following circle in the middle of Mac display. 

Version 0.9 on Catalina 10.15.7 did not have this problem. I just updated today, and will most likely downgrade to 0.9 till this is fixed. 

Also the snooze button is only shown during the first 10 seconds before the actual alert is started. It would be great if one can have the snooze button shown during the entire alert.   

<img width="790" alt="Screenshot 2022-06-11 at 16 28 19" src="https://user-images.githubusercontent.com/702417/173192320-4da83ff9-f5c3-4db5-8b58-a5ff10f51662.png">

**Comment by joja19** [comment]
Looks like the new version is a bit opinionated about full screens and what should be displayed in the about. Although an approach of less is more is good at some times, but when it comes to eye rest, only more is more. I'm bit discouraged by v 1.1.0 and I have downgraded to 0.9. The new version is not always better.

<img width="1137" alt="Screenshot 2022-06-11 at 16 43 18" src="https://user-images.githubusercontent.com/702417/173192702-20437c77-be2d-4a73-804c-be0fe84fff3f.png">

**Comment by tom-james-watson** [comment]
This is the intended functionality, so closing this.

You want to look at the "Show backdrop" setting under "Customization". If you turn it on and set the backdrop to the same colour as the break popup and turn opacity to full, it will look exactly the same as the earlier versions.

Please remember that this is a free application provided by somebody working for free in their spare time and so you should adjust both your expectations and maybe your tone accordingly.
