### ISSUE TITLE
add an optional limit to how many times you can postpone a break

### ISSUE THREAD

**Issue by tom-james-watson** [tom-james-watson/breaktimer-app#17]
Add an extra option after "postpone length" for "postpone limit". This should be a dropdown with options [1, 2, 3, 4, 5, no limit].

This should help stop you from abusing the postpone function.

**Comment by mgmmgm14** [comment]
"This should help stop you from abusing the postpone function."

I really need this, otherwise the only options are to disable postpone or to end up abusing postpone :(

**Comment by tom-james-watson** [comment]
This will be released in version 0.6.0 over the next few days
