### ISSUE TITLE
Feature Request: locks break to a fixed time schedule

### ISSUE THREAD

**Issue by thomasvs** [tom-james-watson/breaktimer-app#171]
I work at a company where meetings typically happen at the half hour mark, and I'd like my break timer locked to that steady pulse of every 30 minutes.

There's no way to configure it currently.  You can configure for example an 58/2 interval, but you can't configure it to start that 58 minutes at the top of the hour.

**Comment by tom-james-watson** [comment]
Sorry, this is too niche of a feature and therefore not something I'd be interested in supporting.
