### ISSUE TITLE
 breaktimer icon have non-transparent borders in windows

### ISSUE THREAD

**Issue by soredake** [tom-james-watson/breaktimer-app#172]
How icon should look (1.0.2 version):
![изображение](https://user-images.githubusercontent.com/5204968/194558657-76e69766-dc04-44d3-9c4b-0aa588de7034.png)

How it looks in newer versions:
![изображение](https://user-images.githubusercontent.com/5204968/175327535-898ccc3b-0b4b-414e-b65b-017898d3205e.png)

**Comment by 16Bit-Rahil** [comment]
i dont have this bug... can you better describe the problem?

**Comment by soredake** [comment]
After reinstalling windows i don't having this problem anymore.
