### ISSUE TITLE
Good work

### ISSUE THREAD

**Issue by StefanoChiodino** [tom-james-watson/breaktimer-app#189]
Hey 👋 
I was looking for a way to make a small donation to this project, but I couldn't find one. Instead I'm just opening this ticket on GH to let you know that I really like this app. I hope this is ok :)
I tried several others but this one hit the right simple/functional spot for me.

Great work 👍

**Comment by tom-james-watson** [comment]
Thanks for your kind words. Accepting donations is actually more hassle than it's worth to be honest. Just using the app is thanks enough :)
