### ISSUE TITLE
Graphical artifacts on start of break

### ISSUE THREAD

**Issue by mal-tee** [tom-james-watson/breaktimer-app#194]
**Describe the bug**
When the break first pops up, I always get graphical artifacts under the circle. 

They are visible for approx. a second and seem to be animated. 

**To Reproduce**
1. Click on 'Start break now'

**Screenshots**
![image](https://user-images.githubusercontent.com/45886910/203302402-749ceb87-1478-436d-8942-a93f3d4fdf6b.png) 

**Specs:**
 ```
OS: EndeavourOS Linux x86_64 (Arch Linux)
Kernel: 6.0.9-arch1-1 
Resolution: 1920x1080 (but also happens on 4K monitors)
DE: GNOME 43.1 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Adwaita [GTK2/3] 
CPU: 12th Gen Intel i7-12700H (20) @ 4.600GHz 
GPU: NVIDIA GeForce RTX 3050 Ti Mobile 
GPU: Intel Alder Lake-P
```
```
Name            : breaktimer-bin
Version         : 1.2.0-1
```

**Comment by tom-james-watson** [comment]
Closing because unable to recreate this
