### ISSUE TITLE
Missing space in countdown string

### ISSUE THREAD

**Issue by arthurmcgregor** [tom-james-watson/breaktimer-app#21]
![break app](https://user-images.githubusercontent.com/24260476/72563627-ef95fc00-3912-11ea-85bd-1365a52af4fc.jpg)

Currently `00 : 00: 08`

Should be `00 : 00 : 08`?

**Comment by tom-james-watson** [comment]
Thanks, Arthur! I won't make a whole new release just for this, so it will go out whenever I next make some changes.
