### ISSUE TITLE
Doesn't work on KDE Wayland session

### ISSUE THREAD

**Issue by cthu1hoo** [tom-james-watson/breaktimer-app#214]
**Describe the bug**

I've tried latest version (RPM) on Fedora 37 KDE. Under Wayland, the app seem to start normally, draw systray icon and then does nothing. There's no context menu, and periodic breaks do not trigger.

Under X11 session everything works correctly.

I hope this can be fixed, I'm using your app on all my computers (macos, windows, linux) it's a literal life^Weye saver. :)

System specs:

- Fedora 37 (all latest updates installed)
- Wayland
- AMD Radeon GPU

If it's hard to reproduce, I'll provide any necessary logs and whatever else.

**Comment by IlgazC** [comment]
I have a similar problem under openSUSE Tumbleweed/KDE Wayland here. Breaktimer (snap version) isn't visible at all, there is nothing on the journal except:
systemd[2232]: Started snap.breaktimer.breaktimer.24879827-fd10-4254-bab4-9ebc7d96563c.scope.

KDE information:
Operating System: openSUSE Tumbleweed 20230424
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.105.0
Qt Version: 5.15.9
Kernel Version: 6.2.12-1-default (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i5-5200U CPU @ 2.20GHz
Memory: 7.7 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 5500
Manufacturer: Hewlett-Packard
Product Name: HP Pavilion 13 x360 PC
System Version: 0977120000405F00000410180

**Comment by IlgazC** [comment]
It is fixed with the current KDE under openSUSE Tumbleweed (which is a rolling release). However, I don't see break reminders so far.

**Comment by tom-james-watson** [comment]
I will be bumping some dependencies like electron and publishing a new version, which may help.
