### ISSUE TITLE
Face problems when building from npm

### ISSUE THREAD

**Issue by hjenryin** [tom-james-watson/breaktimer-app#216]
First, thank you a lot for the wonderful app! It helps me a lot!
I'd like to make some contributions, but I faced several problems when building with npm according to the instructions in `DEVELOPMENT.md`.

**To Reproduce**
1.  `npm i`
  After running this as instructed in `DEVELOPMENT.md`, I get the following error:
  ```
  npm WARN ERESOLVE overriding peer dependency
  npm WARN ERESOLVE overriding peer dependency
  npm WARN ERESOLVE overriding peer dependency
  npm WARN ERESOLVE overriding peer dependency
  npm WARN ERESOLVE overriding peer dependency
  npm WARN ERESOLVE overriding peer dependency
  npm WARN ERESOLVE overriding peer dependency
  npm ERR! code ERESOLVE
  npm ERR! ERESOLVE could not resolve
  npm ERR!
  npm ERR! While resolving: file-loader@3.0.1
  npm ERR! Found: webpack@5.65.0
  npm ERR! node_modules/webpack
  npm ERR!   dev webpack@"^5.65.0" from the root project
  npm ERR!   peer webpack@"4.x.x || 5.x.x" from @webpack-cli/configtest@1.0.4
  npm ERR!   node_modules/@webpack-cli/configtest
  npm ERR!     @webpack-cli/configtest@"^1.0.4" from webpack-cli@4.8.0
  npm ERR!     node_modules/webpack-cli
  npm ERR!       dev webpack-cli@"^4.8.0" from the root project
  npm ERR!       3 more (@webpack-cli/configtest, @webpack-cli/info, @webpack-cli/serve)
  npm ERR!   11 more (babel-loader, css-loader, ...)
  npm ERR!
  npm ERR! Could not resolve dependency:
  npm ERR! peer webpack@"^4.0.0" from file-loader@3.0.1
  npm ERR! node_modules/file-loader
  npm ERR!   dev file-loader@"^3.0.1" from the root project
  npm ERR!
  npm ERR! Conflicting peer dependency: webpack@4.46.0
  npm ERR! node_modules/webpack
  npm ERR!   peer webpack@"^4.0.0" from file-loader@3.0.1
  npm ERR!   node_modules/file-loader
  npm ERR!     dev file-loader@"^3.0.1" from the root project
  npm ERR!
  npm ERR! Fix the upstream dependency conflict, or retry
  npm ERR! this command with --force or --legacy-peer-deps
  npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
  ```
  It seems that there are some conflicts in the dependency. I'm not sure if this should be expected, because I thought the dependabot should take care of this.
  I tried as what is done in [this comment](https://github.com/tom-james-watson/breaktimer-app/issues/7#issuecomment-1188479878) to use `npm i reactstrap --legacy-peer-deps`. This time it succeeds. I know this flag may introduce some potential malfunctions, and I'm not quite sure if this is the correct way of doing so.

  2. `npm run dev`
  The outputs from command line seems fine except some deprecation warning (recommending to change `/` to `math.div` in _Dart Sass_, and `[DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.`). However, when I follow the loopback to http://127.0.0.1:1212/, the title reads "Error" and the only content is "Cannot GET /". 
  It seems that there's something wrong with the code when dealing with the web api. But it also might be caused by the potential malfunction in the previous step. 

**Expected behavior**
I suppose the UI should show up after going to http://127.0.0.1:1212/.

**Specs:**
I tried this out also on the laptop of a friend of mine, and the same thing happened.
Spec1: Windows 11 22H2, npm 8.15.0 and npm 9.5.1 both failed.
Spec2: WIndows 10 21H2, npm 8.15.0.

**Comment by tom-james-watson** [comment]
Yes, the solution to install dependencies is to do `npm i --legacy-peer-deps`.

When doing `npm run dev`, the app should just open. You shouldn't be navigating to that URL, that is simply the webpack dev server and is loaded by electron. You should just see the app start and should be available in the system tray.

**Comment by hjenryin** [comment]
Ah I see. Thank you for your clarification!
