### ISSUE TITLE
Timing is not accurate.

### ISSUE THREAD

**Issue by Triantafullenia-Doumani** [tom-james-watson/breaktimer-app#219]
**Describe the bug**
I've been using the app for a few weeks now (thanks for that), however, the time freezes, so the waiting time until the next break period is not accurate.

Some examples:

* I get 'Next break in 43 minutes' for at least 10 minutes

* [9:30]: Next break in 45 minutes
[10:15]: Next break in 30 minutes

**Expected behavior**
Correct time remaining until the next break period.

**Specs:**
OS version: Ubuntu 20.04.4 LTS
App version: 1.2.0 (snap)

**Additional context**
The problem only occurs during work periods (no break periods), and it's still the same whether I use my computer or not.

**Comment by tom-james-watson** [comment]
Closing this out due to age and because the logic around how breaks works has recently had some changes. Please re-report if you still see this issue.
