### ISSUE TITLE
Publish breaktimer to microsoft store in msix format

### ISSUE THREAD

**Issue by soredake** [tom-james-watson/breaktimer-app#223]
**Describe the bug**
Publishing breaktimer to microsoft store in msix format will allow easy install/update/uninstall, and also [will sign you package](https://www.advancedinstaller.com/msix-digital-signing.html) so windows user will no longer see a prompt saying that app is unrecognized.

**Additional context**
Example benefits of msix: https://github.com/felixrieseberg/windows95/issues/221 https://learn.microsoft.com/en-us/windows/msix/overview#key-features
Additional info: https://www.advancedinstaller.com/msix-publish-microsoft-store.html https://www.advancedinstaller.com/msix-digital-signing.html

**Comment by tom-james-watson** [comment]
Hello. This won't happen until the electron-builder upstream has support for building msix: https://github.com/electron-userland/electron-builder/issues/5021, unfortunately.

**Comment by soredake** [comment]
@tom-james-watson .msi/.exe can be repacked into .msix https://learn.microsoft.com/en-us/windows/msix/packaging-tool/tool-overview

**Comment by tom-james-watson** [comment]
I'm afraid for me this is low priority at the moment. If someone can provide a pull request with an end to end demo of how to do it, maybe it might get done.
