### ISSUE TITLE
Flatpak & Scoop

### ISSUE THREAD

**Issue by trymeouteh** [tom-james-watson/breaktimer-app#224]
Please release the app in scoop which is a windows package manager and as a flatpak which is a linux package manager.

**Comment by tom-james-watson** [comment]
When electron-builder / flatpak support publishing builds to flathub, I'll add support for it. See https://www.electron.build/configuration/flatpak.

I doubt scoop will happen unless someone makes a pull request with it implemented.

**Comment by IkelAtomig** [comment]
James, Did you try building though if it throws error or not ?
