### ISSUE TITLE
Render settings with dark mode based on system preferences

### ISSUE THREAD

**Issue by fluffynuts** [tom-james-watson/breaktimer-app#227]
Please implement a toggle for dark mode in the dialogs. It looks like Blueprint has it built-in - the demo at https://codesandbox.io/p/sandbox/blueprint-sandbox-2023-fjo3z4?file=%2Fsrc%2FApp.tsx%3A11%2C41 looks simple, but I'm not a react dev, so I'm actually having a hard time figuring out exactly _where_ the meat of the toggle happens - I can see state and a callback, but I don't know what's observing that flag to actually switch out themes

Also, I'm not sure if this already "just works", eg, on OSX. I'm running BreakTimer on Windows 11, with all the dark theming stuff enabled.

**Specs:**
 - OS version: Windows 11

**Comment by Hrushal-Nikhare** [comment]
hey
you can already implement dark mode just change the colors
settings > Customization

**Comment by Hrushal-Nikhare** [comment]
i use 58, 64, 90 (RGB) as bg with white 255 , 255 , 255 (RGB) for text that does it for me

**Comment by tom-james-watson** [comment]
Completed in https://github.com/tom-james-watson/breaktimer-app/pull/231. Check out the screenshot there for what it looks like. Will publish a new version soon. Note that there is a but that prevents this from working properly on linux.

**Comment by fluffynuts** [comment]
@tom-james-watson thanks (:

**Comment by fluffynuts** [comment]
> hey you can already implement dark mode just change the colors settings > Customization

not really - dark mode implies changing the _background_ as per #231 - there's no option for that in the Customization panel - though perhaps this is a "simple" workaround for dark mode on linux, @tom-james-watson ?

![image](https://github.com/tom-james-watson/breaktimer-app/assets/4669340/01a5af92-f215-4102-ac01-142591ac1f00)

**Comment by fluffynuts** [comment]
> hey you can already implement dark mode just change the colors settings > Customization

not really - dark mode implies changing the _background_ as per #231 - there's no option for that in the Customization panel 

![image](https://github.com/tom-james-watson/breaktimer-app/assets/4669340/d5837cbe-d587-44e6-bc42-d13825079838)

though perhaps this is a "simple" workaround for dark mode on linux, @tom-james-watson ? I'd personally prefer something a bit darker, considering the palette of dark background colors on my system:

1. GitHub: 
![image](https://github.com/tom-james-watson/breaktimer-app/assets/4669340/d5837cbe-d587-44e6-bc42-d13825079838)
2. WebStorm:
![image](https://github.com/tom-james-watson/breaktimer-app/assets/4669340/6774c4c2-ffed-435c-8dcb-5f00906d35ab)
3. Slack:
![image](https://github.com/tom-james-watson/breaktimer-app/assets/4669340/7d49d268-c239-41c1-a807-f6e0134bd9bf)
4. Windows settings:
![image](https://github.com/tom-james-watson/breaktimer-app/assets/4669340/d2256051-63be-4fba-9116-473a2eedf66e)

All different colors 😅
