### ISSUE TITLE
Add maintainers

### ISSUE THREAD

**Issue by holocronweaver** [tom-james-watson/breaktimer-app#229]
Seems this repo is not being actively maintained. 

So the project can continue without depending on any one contributor, please:
- [ ] transfer it to a Github org
- [ ] add at least two new maintainers

**Comment by tom-james-watson** [comment]
If there are people interested in fixing bugs and or adding features then they are already perfectly capable of making PRs.

**Comment by holocronweaver** [comment]
First off, want to say I use breaktimer daily and am very grateful for the work you have done for the project! It has single-handedly eliminated my back pain.

Adding maintainers can help improve the robustness of an open source project. If issues and PRs are opened but aren't always being attended to in a timely manner, adding maintainers can reduce the load on the primary maintainer and increase turnaround time. But more importantly, adding maintainers makes it so the project can continue even if the original maintainer is no longer available, without a costly fork. (And maintenance forks are costly - they lose stars on Github, require getting permissions for websites, CI, OS package repos, etc., which can take months, or else duplicating all that and hoping Google will surface the fork.)

If the issue is there aren't any good maintainer candidates that come to mind, consider posting a 'help wanted' issue and asking smaller contributors if they'd be interested in helping with issues and/or PRs.

**Comment by tom-james-watson** [comment]
There has been a message of "Looking for contributors" for a long time at the top of the README, but so far nobody has offered. I'd be very happy to add collaborators if anyone offers to step up.
