### ISSUE TITLE
Break TImer fails to initiate a break.

### ISSUE THREAD

**Issue by ershov** [tom-james-watson/breaktimer-app#230]
**Describe the bug**
At some point the app stops showing its break window. If I click on the app icon, it says that the next break is in less than a minute but that actually never happens.

**To Reproduce**
I don't know how to reproduce it, the app just falls into that state quite regularly.

**Specs:**
 - OS version: Ventura 13.4 and multiple earlier versions.

**Comment by adrianh** [comment]
Yeah — I still see this one also.
