### ISSUE TITLE
Windows 11 - No Fullscreen  with "Notify me with" 

### ISSUE THREAD

**Issue by qisbic** [tom-james-watson/breaktimer-app#232]
In Windows 11 (BreakTImer 1.2.0)

Break Settings -> Notify me with

there are only 2 only "Pop break" and  "Simple notification"

Is there no FULLSCREEN option as described on the home GitHub page?

**Comment by tom-james-watson** [comment]
The full screen break window was replaced with the popup option. You can achieve a "full screen" look if you want by doing this: https://github.com/tom-james-watson/breaktimer-app/issues/169#issuecomment-1153114893
