### ISSUE TITLE
It dose not lock my screen when i am using the Youtube.

### ISSUE THREAD

**Issue by mangesh123vispute** [tom-james-watson/breaktimer-app#238]
**Describe the bug**
It dose not lock my screen when i am using the Youtube.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Specs:**
 - OS version: [e.g. macOS 11.6]

**Additional context**

**Comment by tom-james-watson** [comment]
There's nothing that should stop this from working as expected - I just tested and it does indeed start a break whilst in a fullscreen youtube video. Probably what is happening is that you have the idle reset setting turned on (it's on by default).

What happens is that if you are watching youtube and don't interact with your computer at all, eg by moving the mouse or typing, for longer than the idle reset countdown then a break will not happen. The idea is that if you take a break by not using your computer then the break countdown will reset when you return to your computer. If this interferes with how you want to use the app, then I suggest just turning off idle reset.
