### ISSUE TITLE
No settings GUI on elementary os (built on ubuntu 18.04)

### ISSUE THREAD

**Issue by Julianouyang** [tom-james-watson/breaktimer-app#24]
Hi,

I really enjoyed the chrome version of breaktimer, but the desktop version seems not work very well on my linux system. The setting GUI would not pop up no matter how I try to open it. The default alert works.

I tried to install it from snap store and .deb file, but neither of them worked.

Breaktimer version: 0.6.2
My system: elementary OS 5.1 Hera, built on Ubuntu 18.04.3 LTS

I know my information might be limited for debugging, but I'd like to provide more if necessary.

**Comment by tom-james-watson** [comment]
I will try and check this out in a vm soon. I'm not doing anything crazy to render the settings and I assume elementary is perfectly capable of rendering electron browser windows, so hopefully it's an easy fix.

**Comment by tom-james-watson** [comment]
So I tried this out - is your problem that you cannot see the icon in the system tray? I had understood that you meant pressing "Settings" from the tray icon wasn't working. It looks like Elementary does not support app indicators (which is what linux uses to show tray icons) out of the box, which would be why you can't see that.

This will also be a problem for any other linux distros that don't support app indicators, such as any gnome installation that doesn't come with or an app indicator extension or has had it installed by the user. At least Ubuntu does come pre-bundled with app indicator support.

Really the proper way to solve this is change how the app works on certain linux distros to not depend on a tray icon, though this would require some major reworking.

**Comment by Julianouyang** [comment]
> So I tried this out - is your problem that you cannot see the icon in the system tray?

I can see the icon from system tray. The issue is it's not responding. Nothing happened after I click the icon. Do you think this relates to the app indicator?

**Comment by tom-james-watson** [comment]
Have you installed a special extension or program to add app indicators? Elementary doesn't seem to have any support at all for them out of the box.

**Comment by cantalupo555** [comment]
> > So I tried this out - is your problem that you cannot see the icon in the system tray?
> 
> I can see the icon from system tray. The issue is it's not responding. Nothing happened after I click the icon. Do you think this relates to the app indicator?

Here it works very well on Solus Linux
I'm using gnome as a graphical interface.

**Comment by cantalupo555** [comment]
`cantalupo@cantalupo ~/Downloads/opt/BreakTimer $ ./breaktimer 
22:39:48.770 › Checking for updates...
22:39:48.777 › APPIMAGE env is not defined, current application is not an AppImage
GET_SETTINGS
GET_SETTINGS
SET_SETTINGS {
  settings: {
    autoLaunch: true,
    backgroundColor: '#16a085',
    breakFrequency: '1899-12-31T02:20:06.000Z',
    breakLength: '1899-12-31T02:19:46.000Z',
    breakMessage: 'Rest your eyes. Stretch your legs. Breathe. Relax.',
    breakTitle: 'Time for a break!',
    breaksEnabled: true,
    endBreakEnabled: true,
    gongEnabled: true,
    idleResetEnabled: true,
    idleResetLength: '1899-12-31T02:24:36.000Z',
    idleResetNotification: false,
    notificationClick: 'SKIP',
    notificationType: 'POPUP',
    postponeLength: '1899-12-31T02:22:36.000Z',
    postponeLimit: 0,
    textColor: '#ffffff',
    workingHoursEnabled: true,
    workingHoursFriday: true,
    workingHoursFrom: '1899-12-31T11:19:36.000Z',
    workingHoursMonday: true,
    workingHoursSaturday: false,
    workingHoursSunday: false,
    workingHoursThursday: true,
    workingHoursTo: '1899-12-31T20:19:36.000Z',
    workingHoursTuesday: true,
    workingHoursWednesday: true
  }
}
SET_SETTINGS {
  settings: {
    autoLaunch: true,
    backgroundColor: '#16a085',
    breakFrequency: '1899-12-31T02:20:06.000Z',
    breakLength: '1899-12-31T02:19:46.000Z',
    breakMessage: 'Rest your eyes. Stretch your legs. Breathe. Relax.',
    breakTitle: 'Time for a break!',
    breaksEnabled: true,
    endBreakEnabled: true,
    gongEnabled: true,
    idleResetEnabled: true,
    idleResetLength: '1899-12-31T02:24:36.000Z',
    idleResetNotification: false,
    notificationClick: 'SKIP',
    notificationType: 'POPUP',
    postponeLength: '1899-12-31T02:22:36.000Z',
    postponeLimit: 0,
    textColor: '#ffffff',
    workingHoursEnabled: false,
    workingHoursFriday: true,
    workingHoursFrom: '1899-12-31T11:19:36.000Z',
    workingHoursMonday: true,
    workingHoursSaturday: false,
    workingHoursSunday: false,
    workingHoursThursday: true,
    workingHoursTo: '1899-12-31T20:19:36.000Z',
    workingHoursTuesday: true,
    workingHoursWednesday: true
  }
}
Send event PLAY_START_GONG []
GET_SETTINGS
GET_BREAK_END_TIME
Send event PLAY_START_GONG []
Send event PLAY_START_GONG []
GET_SETTINGS
GET_BREAK_END_TIME
Send event PLAY_START_GONG []
Send event PLAY_START_GONG []
GET_SETTINGS
GET_BREAK_END_TIME
Send event PLAY_START_GONG []
Send event GET_SETTINGS_SUCCESS [
  {
    autoLaunch: true,
    breaksEnabled: false,
    notificationType: 'POPUP',
    notificationClick: 'SKIP',
    breakFrequency: '1899-12-31T02:20:06.000Z',
    breakLength: '1899-12-31T02:19:46.000Z',
    postponeLength: '1899-12-31T02:22:36.000Z',
    postponeLimit: 0,
    workingHoursEnabled: false,
    workingHoursFrom: '1899-12-31T11:19:36.000Z',
    workingHoursTo: '1899-12-31T20:19:36.000Z',
    workingHoursMonday: true,
    workingHoursTuesday: true,
    workingHoursWednesday: true,
    workingHoursThursday: true,
    workingHoursFriday: true,
    workingHoursSaturday: false,
    workingHoursSunday: false,
    idleResetEnabled: true,
    idleResetLength: '1899-12-31T02:24:36.000Z',
    idleResetNotification: false,
    gongEnabled: true,
    breakTitle: 'Time for a break!',
    breakMessage: 'Rest your eyes. Stretch your legs. Breathe. Relax.',
    backgroundColor: '#16a085',
    textColor: '#ffffff',
    endBreakEnabled: true
  }
]
SET_SETTINGS {
  settings: {
    autoLaunch: true,
    backgroundColor: '#16a085',
    breakFrequency: '1899-12-31T02:20:06.000Z',
    breakLength: '1899-12-31T02:19:46.000Z',
    breakMessage: 'Rest your eyes. Stretch your legs. Breathe. Relax.',
    breakTitle: 'Time for a break!',
    breaksEnabled: true,
    endBreakEnabled: true,
    gongEnabled: true,
    idleResetEnabled: true,
    idleResetLength: '1899-12-31T02:24:36.000Z',
    idleResetNotification: false,
    notificationClick: 'SKIP',
    notificationType: 'POPUP',
    postponeLength: '1899-12-31T02:22:36.000Z',
    postponeLimit: 0,
    textColor: '#ffffff',
    workingHoursEnabled: false,
    workingHoursFriday: true,
    workingHoursFrom: '1899-12-31T11:19:36.000Z',
    workingHoursMonday: true,
    workingHoursSaturday: false,
    workingHoursSunday: false,
    workingHoursThursday: true,
    workingHoursTo: '1899-12-31T20:19:36.000Z',
    workingHoursTuesday: true,
    workingHoursWednesday: true
  }
}
Send event PLAY_START_GONG []
GET_SETTINGS
GET_BREAK_END_TIME
Send event PLAY_START_GONG []
Send event GET_SETTINGS_SUCCESS [
  {
    autoLaunch: true,
    breaksEnabled: false,
    notificationType: 'POPUP',
    notificationClick: 'SKIP',
    breakFrequency: '1899-12-31T02:20:06.000Z',
    breakLength: '1899-12-31T02:19:46.000Z',
    postponeLength: '1899-12-31T02:22:36.000Z',
    postponeLimit: 0,
    workingHoursEnabled: false,
    workingHoursFrom: '1899-12-31T11:19:36.000Z',
    workingHoursTo: '1899-12-31T20:19:36.000Z',
    workingHoursMonday: true,
    workingHoursTuesday: true,
    workingHoursWednesday: true,
    workingHoursThursday: true,
    workingHoursFriday: true,
    workingHoursSaturday: false,
    workingHoursSunday: false,
    idleResetEnabled: true,
    idleResetLength: '1899-12-31T02:24:36.000Z',
    idleResetNotification: false,
    gongEnabled: true,
    breakTitle: 'Time for a break!',
    breakMessage: 'Rest your eyes. Stretch your legs. Breathe. Relax.',
    backgroundColor: '#16a085',
    textColor: '#ffffff',
    endBreakEnabled: true
  }
]

`

**Comment by cantalupo555** [comment]
![](https://i.imgur.com/yJanext.png)
![](https://i.imgur.com/qXAk1mI.png)
![](https://i.imgur.com/yJanext.png)

**Comment by Julianouyang** [comment]
> Have you installed a special extension or program to add app indicators? Elementary doesn't seem to have any support at all for them out of the box.

No, not I'm aware of. 
Btw, can I change settings in command line? For me it would help too.

**Comment by tom-james-watson** [comment]
See https://github.com/tom-james-watson/breaktimer-app/issues/25 - you can now enable/disable breaktimer with `breaktimer enable` and `breaktimer disable` from the cli.

Then, for environments that don't support system trays at all, if you simply run the app a second time it will open the settings window allowing you to actually configure the app. This is in the process of being published and will be available soon in version 0.7.0.

Please let me know if this works for you.
