### ISSUE TITLE
[FEATURE] Blur background + remain until user clicks close

### ISSUE THREAD

**Issue by bilogic** [tom-james-watson/breaktimer-app#243]
Hi,

Great app here! Just started using it yesterday and loving it already!

As we cannot anticipate when the pop up will show, it would help if the background can be _configured_ to be blurred in case there are some sensitive info we were working on.

In addition, we should also be able to _configure_ the pop up to remain until user clicks it (Today, it closes by itself after the break period is complete). This way, the blurred background remains until we return. And we would also know if someone were to click to close the pop up.

**Comment by torpesco** [comment]
One workaround: Use a hotkey to lock your screen if you're walking away. At least, I know it works on Mac using `Command-Control-Q`.

**Comment by bilogic** [comment]
Sure, I'm all for absolute security. But in some cases, blurring would be sufficient. Locking would mean I no longer see that the break time is over. :)

**Comment by tom-james-watson** [comment]
If you want to hide your desktop then you can use the background opacity feature to set a solid background colour for the break window. The rest of your requests are kind of too niche. I agree that you should just lock your screen if you're not in an environment where you can leave your computer unlocked. The app isn't ever going to be a secure lock screen, of course.
