### ISSUE TITLE
Rest break active immediately upon unlocking after long period (macOS 14 / Sonoma)

### ISSUE THREAD

**Issue by torpesco** [tom-james-watson/breaktimer-app#249]
**Describe the bug**
After being away from my computer for a longer stretch (lunch, first unlock in the morning, etc), when I unlock it, I find a rest break active.

**To Reproduce**
1. Configured for a 1 minute break every 15 minutes.
2. Go for lunch. Take longer than 15 minutes.
3. Unlock computer
4. Rest break is active (not the initial display with the snooze option, but the display with the break active and the 'end' option)
    - (Edit: May be more accurate to say the timer is lower than it should be. I experienced one time where the break started five minutes after unlocking my computer.)

**Expected behavior**
Next rest break should start 15 minutes after unlocking, since I've been away from my computer for more than 15 minutes.

**Specs:**
 - OS version: macOS 14.0
   - I don't remember this happening with macOS 13.x.

**Comment by torpesco** [comment]
Wow... Well, I think I've found the issue. 🙄

Very likely #215.

Just went to tweak something in the settings and clued in to the "idle reset" tab. It was set to 21:05:00 instead of 00:05:00 (similar to the times in the screenshot in 215).

I bet it's been like this since August for me (when I posted a "me too" on 215). Strange coincidence I only started noticing it more after the macOS 14 update.

**Comment by tom-james-watson** [comment]
Yeah, I've not had a chance to dig into why that happens.

It seemed to be something to do with timezones.
