### ISSUE TITLE
Add cli commands to disable/enable

### ISSUE THREAD

**Issue by jimbolimbo13** [tom-james-watson/breaktimer-app#25]
Not really an issue, just a question: are there cli commands for Breaktimer?
I'd love to be able to write some kind of script to disable it when I join a video call (especially if I'm screensharing)

**Comment by tom-james-watson** [comment]
There is no way to do this at the moment but if we limit it to `breaktimer disable` / `breaktimer enble` I don't think it would be too difficult. Something similar had been suggested in the past, too.

**Comment by tom-james-watson** [comment]
I've just added support for `breaktimer disable` and `breaktimer enable` and am in the process of publishing it (v0.7.0).

**Comment by jimbolimbo13** [comment]
Awesome! I’ll stay tuned. Many thanks!

**Comment by tom-james-watson** [comment]
It's already published so you should be able to auto-update to it if you restart the app, if you are using one of the auto-updating versions of the app. If not, grab it from https://breaktimer.app

**Comment by jimbolimbo13** [comment]
Not sure if it's working:
I set Breaktimer to disabled, then closed it, then ran "breaktimer enable"
in the terminal and it looks like it just opens Breaktimer in whatever the
setting was when it was closed. I've attached a screenshot showing what I
tried to do and the state of Breaktimer as well as the About page. (I have
the Snap installation, and it looks like it auto-updated for me)

(also, if I need to open a separate issue for this, let me know)

**Comment by tom-james-watson** [comment]
You need to upload pictures on the actual github issue page; attaching them in an email reply won't work.

When you say "then closed it" - do you mean you closed the settings window or do you mean you quit the app. `breaktimer enable/disable` will only work if the app is already running.

Actually it does look like this is not working with the snap version.

**Comment by tom-james-watson** [comment]
https://github.com/tom-james-watson/breaktimer-app/issues/26

**Comment by jimbolimbo13** [comment]
Hi Tom, just wanted to say thanks for adding this functionality! I eventually switched from using the snap package to using the .deb package and the cli command works flawlessly.
