### ISSUE TITLE
Hardcoded path causes notarization to fail on arm64 (and generally different targets)

### ISSUE THREAD

**Issue by nc7s** [tom-james-watson/breaktimer-app#251]
Released `.app` is built for x86_64, electron-builder puts artifacts for it in `release/mac`. But on arm64 aka M1/2, it's `release/mac-arm64`. A rather cryptic `spawn ditto ENOENT` error is thus caused by this line:

https://github.com/tom-james-watson/breaktimer-app/blob/fa042f8a510d2335cdf8e48f3d18bde3d17ac65c/internals/scripts/Notarize.js#L14

It can of course be fixed with a query into `electron-builder`, but there's another route: to build a universal binary. This would introduce yet another ~100MiB to the final `.app` (from `Electron Framework`), but it's already ~200 anyway. This can be achieved with:

```diff
--- a/package.json
+++ b/package.json
@@ -66,7 +66,12 @@
       "gatekeeperAssess": false,
       "hardenedRuntime": true,
       "target": [
-        "dmg"
+        {
+          "target": "dmg",
+          "arch": [
+            "universal"
+          ]
+        }
       ]
     },
     "dmg": {
```

By the way, `electron-notarize` has changed to `@electron/notarize`.

**Comment by tom-james-watson** [comment]
How notarization works was recently reworked.
