### ISSUE TITLE
Can't open settings

### ISSUE THREAD

**Issue by lindsayalexandra14** [tom-james-watson/breaktimer-app#252]
**Describe the bug**
I have BreakTimer for my macbook pro and I can't open the settings. I assume I go to the application in my finder and click on it to get there but nothing happens when I do.

**To Reproduce**
1. Go to Applications in Finder on Mac
2. Click on BreakTimer
3. Settings does not open

**Expected behavior**
I expect the Settings to open so I can adjust them

**Screenshots**
n/a

**Specs:**
 - OS version: macOS Ventura 13.6
 - Apple M1 Max

**Additional context**
Please help, thanks

**Comment by tom-james-watson** [comment]
Breaktimer is a system tray application. You need to click the icon in the system tray and press settings.

**Comment by lindsayalexandra14** [comment]
Got it. Thank you!

Lindsay
