### ISSUE TITLE
Tauri as build target

### ISSUE THREAD

**Issue by 6543** [tom-james-watson/breaktimer-app#253]
Would it be accepted to have https://tauri.app/ as build option. I would be interested in trying to contrubuting it.

**Comment by tom-james-watson** [comment]
It wouldn't make sense to have two different targets. I've been keeping an eye on Tauri for a while and think it would be great if the app were to just be fully ported to Tauri. I've not assessed whether all of the features are there for that to happen yet, though.

If you're interested, feel free to explore and let me know if it looks doable. That would be a good first step 🙂

**Comment by 6543** [comment]
a full port should be even easyer - I'll play around and let you know :)
the "two build" targets is if you wana keep electron (and did occurred to me to be much likelier accepted :) )

**Comment by tom-james-watson** [comment]
Would keep the old version around as a download for a while if we ever did migrate - no need to remove them or course!

**Comment by tom-james-watson** [comment]
I'm going to close this out - I don't think migrating to Tauri at this point really makes sense. It would be a huge amount of work for little real gain.

**Comment by frontmesh** [comment]
> I'm going to close this out - I don't think migrating to Tauri at this point really makes sense. It would be a huge amount of work for little real gain.

Hi @tom-james-watson , just wondering — what makes Tauri offer no significant improvements in performance, memory and file size? 

I noticed the Mac .dmg is over 200 MB and installs to more than 400 MB, which seems quite large for an app of this type.
