### ISSUE TITLE
cli args for enable/disable don't work with snap version of the app

### ISSUE THREAD

**Issue by tom-james-watson** [tom-james-watson/breaktimer-app#26]

**Comment by jimbolimbo13** [comment]
re-adding my comments here.
1. Set Breaktimer to "disabled"
2. Completely quit the app (quit it from system tray)
3. ran command `breaktimer enable`
4. app starts back up but is still disabled
![breaktimer_enable_broken](https://user-images.githubusercontent.com/3618494/73748945-6bbc7c00-4728-11ea-8a57-6d2e45fd28b4.png)

**Comment by tom-james-watson** [comment]
Yeah you shouldn't completely quit the app. `breaktimer disable` and `breaktimer enable` only work if the app is already running.

**Comment by jimbolimbo13** [comment]
Oh, I had tried quitting it because if I tried the cli while it was open, it just opened the settings saying the app was already open
![breaktimer_cli](https://user-images.githubusercontent.com/3618494/73752708-6ca4dc00-472f-11ea-835d-d3ad82dfd108.png)

**Comment by tom-james-watson** [comment]
Yup - that's the bug this issue is for
