### ISSUE TITLE
No tray icon in Plasma 6

### ISSUE THREAD

**Issue by giovanniPepi** [tom-james-watson/breaktimer-app#261]
**Describe the bug**
App has no tray icon when the session is Wayland

**To Reproduce**
1. Start a Wayland Session
2. Start BreakTimer AppImage
3. Confirm the icon on system tray

**Expected behavior**
Normal Breaktimer mug as it was in Xorg

**Screenshots**
![image](https://github.com/tom-james-watson/breaktimer-app/assets/5255535/814295f7-bd2c-4f71-b79c-3ef0f45b5666)

**Specs:**
 - OS version:
ArchLinux
![image](https://github.com/tom-james-watson/breaktimer-app/assets/5255535/66e733cf-dcc7-4390-8475-7eb65e42d506)

Installed from AppImage
https://aur.archlinux.org/packages/breaktimer-appimage

**Additional Information**
BreakTimer is running via XWayland

`$ xlsclients`
arch  breaktimer

**Comment by giovanniPepi** [comment]
On further investigation I think this might be a plasma-6 issue. I logged in via Xorg and the icon wasn't there

https://pointieststick.com/2023/08/12/how-all-this-icon-stuff-is-going-to-work-in-plasma-6/

**Comment by tom-james-watson** [comment]
OK, let's keep an eye on it. The app is overdue some bumps to dependencies like Electron that might help things like this.

**Comment by tom-james-watson** [comment]
Will close this out. 1.3.0 bumped a lot of dependencies so hopefully if this was still an issue then it resolved it.
