### ISSUE TITLE
no settings menu, can't uninstall

### ISSUE THREAD

**Issue by aileenholmes** [tom-james-watson/breaktimer-app#264]
**Describe the bug**

Hello, I am using the Mac version of your software.

1. Unable to quit: BreakTimer keeps popping up at inopportune times like when I am presenting in a Teams meeting. I am only able to "snooze". I am unable to quit out of the program before the meeting.

2. No Settings Menu: When I double click on the application, no settings menu comes up so I am unable to change the settings.

3. Unable to uninstall: When I tried to uninstall by putting the application in the trash, my Mac says that it is "unable to move to the Trash because it is open". However, when I bring up the Force Quit menu, the application is not listed.

**Specs:**
 - OS version: macOS Sonoma 14.3.1

**Comment by tom-james-watson** [comment]
The app persists in the system tray, in the top right of your screen. Click on its icon there and you can quit from there.
