### ISSUE TITLE
[macOS] Idle reset is triggered by lock screen below triggering threshold or if disabled

### ISSUE THREAD

**Issue by King-of-Spades** [tom-james-watson/breaktimer-app#27]
## Overview
- Even when I turn off Idle reset in the app it appears to still apply
- Idle reset is triggered below the threshold I set for locking the screen

## Observations
I saw a possibly related issue for Windows as #23. In particular this comment asking for some background info: https://github.com/tom-james-watson/breaktimer-app/issues/23#issuecomment-576230146

> If you lock your screen then immediately unlock it, does it reset? 

In my case on macOS, yes. 

> If so, turn on the idle reset notification option, and it should tell you in the notification how long you were considered idle. How long does it say?

00:00:06 give or take, which I assume is seconds. I configured Idle reset to use 15 minutes. 

## Version info
BreakTimer 0.7.0
macOS Mojave 10.14.6 (I'll probably update this to the latest soon though.)

**Comment by tom-james-watson** [comment]
Thanks for the detailed info - will try and look at this soon!

**Comment by tom-james-watson** [comment]
This will be fixed in 0.7.1 which is going to be published today. Thanks again for the bug report.

**Comment by King-of-Spades** [comment]
Thanks for the fix!
