### ISSUE TITLE
Break Time presets

### ISSUE THREAD

**Issue by IkelAtomig** [tom-james-watson/breaktimer-app#274]
The app is helpful in reminding to take breaks.

It would be better, if there are presets

Such as 

i. Session for 25 Min, Break for 5 mins
ii. Session for 40 Min, Break for 5 mins

This would help during serious workflows apart from the casual ones. Instead of Snooze and Changing Time now and then. This would be easy

This should be accessible via Tray Icon's context menu.

**Comment by tom-james-watson** [comment]
IMO this would unnecessarily overcomplicate the UI.

What I might consider in the future is a way to turn on a pomodoro mode.

**Comment by IkelAtomig** [comment]
That seems fair. Maybe rename the issue as such and reopen ?
