### ISSUE TITLE
Idle timer doesn't work

### ISSUE THREAD

**Issue by karamanliev** [tom-james-watson/breaktimer-app#277]
**Describe the bug**
Idle timer does not work if the value is above 1 seconds

**To Reproduce**
1. Go to 'Settings -> Idle Reset'
2. Set a value which is above 00:00:01s for "Reset break countdown" 
3. Enable notifications
4. Save settings and observe
5. Does not work.

**Expected behavior**
Idle detection should work

**Screenshots**
Video: 

[Screencast from 2024-06-07 17-52-09.webm](https://github.com/tom-james-watson/breaktimer-app/assets/22788016/1071fd78-0aac-4e00-9e98-752f742f4263)

**Specs:**
Arch Linux
Gnome 46 Wayland

**Additional context**
I guess it's a Wayland related issue and electron's `powerMonitor.getSystemIdleTime()` api always returns `0` (one of the many issues on their repo - [34826](https://github.com/electron/electron/issues/34826)) and the computer idle time is not reported correctly. I was able to make it work by running the application with `--enable-features=UseOzonePlatform --ozone-platform=wayland` flags.

Maybe update the README to flag this and the possible workaround?

**Comment by tom-james-watson** [comment]
I will close this out given there is a workaround. Thanks for finding that 👍
