### ISSUE TITLE
app will stop working if idle reset set to zero

### ISSUE THREAD

**Issue by sliker** [tom-james-watson/breaktimer-app#28]
I'm having issue #27 too, and trying to disable the idle reset I put 00:00:00 and get an error (screenshot attached), after I click "OK" the error window show up again, blocking me to close the app, a force close it's needed but app does not work even when I force to quit it and reopen it, the error keeps showing up.
 
<img width="436" alt="Screen Shot 2020-02-11 at 10 38 15 AM" src="https://user-images.githubusercontent.com/186392/74252205-4cd76000-4cbb-11ea-942d-c7186608690a.png">

**Comment by tom-james-watson** [comment]
This will be fixed in 0.7.1 which is going to be published today. Thanks for the bug report!
