### ISSUE TITLE
Notarize the macOS dmg

### ISSUE THREAD

**Issue by MPlugInSpace** [tom-james-watson/breaktimer-app#29]
I tried to install this on a mac and received this error.

> "BreakTime.app" can't be  opened because Apple cannot check if for malicious software.

I am pretty new to  mac and will investigate possible alternative install options but thought you may like to know.

OS: macOS Catalina v10.15.3
Software version: latest (unsure of version number)

![Screenshot 2020-02-12 11 28 03](https://user-images.githubusercontent.com/15203977/74355801-53350d00-4d8b-11ea-8f11-8453c54adf6a.png)

**Comment by tom-james-watson** [comment]
Hello. Where exactly did you download the app from? Is it from https://breaktimer.app or did you download a release file from github? Older versions of the mac app were not signed properly, but it should be now.

Can you right click the .app file in Finder and show me a screenshot of what appears when you press 'Get Info'? Thanks.

**Comment by MPlugInSpace** [comment]
I appologize for not responding to the first comment, I have just now, tried downloading it from both the website and github both resulting in the same message reported. I was able to get it working following the "How to open an app that hasn’t been notarized or is from an unidentified developer" section from https://support.apple.com/en-us/HT202491 .

**Comment by tom-james-watson** [comment]
OK it looks like I've misunderstood the fact that "notarized" is not the same as signing your app.

Looks like some manual work is required to get this working with `electron-builder` - https://github.com/electron-userland/electron-builder/issues/3870

**Comment by EvanGoss** [comment]
I don't have any experience to help with this, but it looks like there has been quite a few posts to https://github.com/electron-userland/electron-builder/issues/3870 since March 2020.

For anyone looking for a work around - I followed the instructions in [DEVELOPMENT.md](https://github.com/tom-james-watson/breaktimer-app/blob/master/DEVELOPMENT.md) to compile my own binary that runs just fine for me.

```
git clone
npm i
npm run package
```
Then open `release/BreakTimer.dmg`

**Comment by tom-james-watson** [comment]
Just to be clear, you can run an un-notarized app by going to `Applications`, right clicking the app and pressing Open. You don't need to build your own package.

The instructions for notarizing the app are here - https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application. I just haven't gotten around to it yet. I'd accept a PR adding the functionality.

**Comment by tom-james-watson** [comment]
As of version the just released version 0.9.0 (https://github.com/tom-james-watson/breaktimer-app/releases/tag/v0.9.0), the macOS app will now be notarized :tada:
