### ISSUE TITLE
[Simple Feature Request] Posture Correction Reminder Each X Minutes

### ISSUE THREAD

**Issue by ibraheemalayan** [tom-james-watson/breaktimer-app#290]
Implement a feature that enables users to configure a reminder sound to prompt them to maintain proper posture.

For reference, consider the Vatobe application (https://vatobe.io).

However, we are unable to utilize Vatobe due to its inability to respect rest periods.

Another approach would be to display a popup message with the voice and a button that says "I corrected my posture"

**Comment by tom-james-watson** [comment]
I don't think this as a feature really fits into the app, sorry
