### ISSUE TITLE
[Feature Request] Allow break window to be moved

### ISSUE THREAD

**Issue by fadookie** [tom-james-watson/breaktimer-app#292]
**Describe the bug**
Some people such as myself prefer to work during "breaks" (I use this app to remind myself to do hand stretches but I can do them one-handed.) Right now the break window sits in the center of the screen and can't be moved or hidden, blocking a lot of what's on the screen.

**To Reproduce**
1. Start a break
2. Try to drag the break window around to move it

**Expected behavior**
Break window should move when it's dragged.

**Specs:**
 - OS version: macOS 14.6.1
 - BreakTimer 1.2.0

**Comment by tom-james-watson** [comment]
The idea with the "popup break" type is that you *can't* interact with the computer whilst the break is happening. Allowing users to do so would be an issue for lots and lots of users.

I'd suggest just using the "simple notification" option instead for your use case.
