### ISSUE TITLE
break feature 

### ISSUE THREAD

**Issue by Mo-Masha** [tom-james-watson/breaktimer-app#293]
it's great that users can set rest timer after certain period of working on the pc 

i suggest adding a feature to 
add long break after certain times the short break is played   
let's say me as a user have set the break timer for 1 minute after each 5 minutes 
i want a feature that allows me to set long break after 4 or 5 cycles of these short breaks 
let it be 15 minutes for example 

i hope you got my idea and all thanks for this great elegant app with this simple interface 
please remember that minor details are what makes the difference between elite and regular ones 

cheers

**Comment by tom-james-watson** [comment]
Thanks for the nice idea but I've given this some thought recently and I would like to just keep this focused on having one kind of break. I don't want to overcomplicate the app.
