### ISSUE TITLE
[Feature Request]  Able to set working hours through midnight

### ISSUE THREAD

**Issue by VetleHvoslef** [tom-james-watson/breaktimer-app#297]
Currently I'm using Working Hours to remind me to stop being on the PC and go to bed. Therefore I would like to be able to set the period of when breaks are enabled from before midnight and after midnight. See the picture for what I am trying to describe as the feature.

![image](https://github.com/user-attachments/assets/4baf821e-ca13-40fc-be2b-28d6efb2d04a)

Is this something you are interested in as a feature? I can try to make a pull request and implement this feature if this is something you are interested?

**Comment by VetleHvoslef** [comment]
Currently if you set for example 05:30 in "Breaks to", it says you are outside of working hours even though you are well inside of working hours (in my example 22:14).

**Comment by tom-james-watson** [comment]
This would be best solved with https://github.com/tom-james-watson/breaktimer-app/issues/128
