### ISSUE TITLE
[Feature request] More customization for working hours

### ISSUE THREAD

**Issue by SqrtWasTaken** [tom-james-watson/breaktimer-app#299]
1. Ability configure the working hours for each day separately, for example on weekdays I don't need it for most of the day since I'm in class, so I would set it to something like 4-11pm, but on the weekends I would want breaks for the whole day.
2. Allow combining disjoint intervals, e.g. 7-10am + 5-9pm. ( #128 )

**Comment by tom-james-watson** [comment]
Good news - version 1.3.0 which has just been released supports all of those things 🎉
