### ISSUE TITLE
Idle Reset still not working as expected when sleeping computer

### ISSUE THREAD

**Issue by ghost** [tom-james-watson/breaktimer-app#30]
I put my computer to sleep, then when I come back, the Break begins. I am guessing something with the idle reset isn't working. This is on a Windows device.

**Comment by tom-james-watson** [comment]
Hello. I'm still perfecting the logic for this in a new version. Hopefully will be released soon.

**Comment by tom-james-watson** [comment]
This should have been fixed in version 0.7.2, which has just been released. Please let me know if you still have issues. Thanks!
