### ISSUE TITLE
Cannot uninstall

### ISSUE THREAD

**Issue by Kscogna** [tom-james-watson/breaktimer-app#302]
Microsoft uninstall is saying that the app is open when I try to uninstall. However, I don't see it running in the system tray or task manager. Our tech support can't uninstall it either. Please list detailed instructions for uninstalling.

**Comment by tom-james-watson** [comment]
I'm sorry but the app must be open if that's what Windows is telling you. Search "BreakTimer" in task manager. It should also have an icon in the system tray where you can right click and press "Quit".

**Comment by Kscogna** [comment]
I'm sorry but I can't find it in Task Manager, except in the "Startup" tab.

**Comment by Kscogna** [comment]
There is no icon in the system tray. There is no indication that it is running n the background in Task Manager.

**Comment by tom-james-watson** [comment]
I'm sorry but I can't really help you, because it's more of a Windows support issue as opposed to BreakTimer. All I can suggest is if you are struggling then reboot into safe mode and uninstall it there?
