### ISSUE TITLE
Package size increased a lot

### ISSUE THREAD

**Issue by debfx** [tom-james-watson/breaktimer-app#304]
**Describe the bug**
At least the Linux package size (haven't checked the others) increased a lot from 1.2.0 to 1.3.0
For example in the .deb package the /opt/BreakTimer/breaktimer binary went from 145M to 1,1G which seems unreasonably large.
It also contains /opt/BreakTimer/resources/app/node_modules/ which could be stripped.

**Comment by wolftune** [comment]
looks fixed in 1.3.1 just now, not sure

**Comment by tom-james-watson** [comment]
Yup, I just fixed this in version 1.3.1. Thanks for point this out. It was a bug with electron. But I also have removed the unnecessary node_modules as you suggested, and also made that app use asar, which both make the app slightly smaller for everyone.

It's still too large, but that's just electron unfortunately.

**Comment by debfx** [comment]
Indeed looks much better now. Thanks a lot!
