### ISSUE TITLE
Feature Idea 

### ISSUE THREAD

**Issue by Charlieelliott24** [tom-james-watson/breaktimer-app#307]
Sometimes I'll disable the app from menu bar (it remains running) - but I'll forget to re-enable it until days later. 
I'd love an option to have it re-enable itself every 12 or 24 hours. 

If it booted up enabled by default, it'd be fairly easy to have GPT write a simple Launchd/plist/AppleScript, but sadly for me, it retains it state after quitting/reopening or restarting computer. 

Another feature idea: is to only allow skip after a certain amount of snoozes or to only allow skip on last snooze attempt.

**Comment by tom-james-watson** [comment]
Have you updated to 1.3.0? Because it addresses this specific idea - you can disable for a specific amount of time via the menu bar, which avoids this issue.
