### ISSUE TITLE
Is there a way to donate?

### ISSUE THREAD

**Issue by VetleHvoslef** [tom-james-watson/breaktimer-app#310]
Fantastic new release! I wondered if there was a way to donate money as a thank you?

**Comment by tom-james-watson** [comment]
That's kind! I've just added a section to the FAQ for this: https://github.com/tom-james-watson/breaktimer-app?tab=readme-ov-file#can-i-donate-to-breaktimer.

**Comment by WesCook** [comment]
I also came here planning to drop a small donation.  Since that is unavailable though, I will instead use this thread to say thank you for the wonderful app.  It does exactly what it needs to, and nothing more.  It's perfect.
