### ISSUE TITLE
Alleged catastrophic crash that locks I/O

### ISSUE THREAD

**Issue by bbkiwi** [tom-james-watson/breaktimer-app#32]
Im not sure the app is causing this but sometimes the computer freezes and does not respond to
mouse or keyboard. It happened once during a break. I notice the following in  `/var/log/syslog
`
```
Feb 19 21:07:35 Ubuntu-Bill-PC gnome-shell[1476]: [AppIndicatorSupport-WARN] Item :1.61/org/ayatana/NotificationItem/BreakTimer1 is already registered
Feb 19 21:08:35 Ubuntu-Bill-PC gnome-shell[1476]: [AppIndicatorSupport-WARN] Attempting to re-register :1.61/org/ayatana/NotificationItem/BreakTimer1; resetting instead
Feb 19 21:08:35 Ubuntu-Bill-PC gnome-shell[1476]: [AppIndicatorSupport-WARN] Item :1.61/org/ayatana/NotificationItem/BreakTimer1 is already registered
```

**Comment by rak-sj** [comment]
A couple weeks ago, this happened to me too - at least 3 times!
I had to "disable" breaktimer (which stopped the problem)
was hard to get out of the lockscreen, but I was able to ctrl-alt-del and get to the task manager and kill the breaktimer executable so my screen was accessible again.
I am running:
Windows 10
ver 1909 (OS Build 18363.592)

I have always loved Break Timer (been using for quite a while now) and hope this can be fixed!'
Thanks!

**Comment by tom-james-watson** [comment]
If anybody sees this issue again, can you please attach your BreakTimer log file so I can debug this? See https://github.com/tom-james-watson/breaktimer-app/#how-can-i-pass-you-my-log-files-to-help-you-debug-an-issue

This is not something I've ever seen.

**Comment by bbkiwi** [comment]
Im away from my computer for a week, but when I get back I'll look for the log

**Comment by Satyrars** [comment]
Sounds similar to what happens to me as well (Windows), although it's pretty rare - and I don't see anything unusual in the logs. I'll send you if I catch it again (and I also need to update from 0.7, I guess).

Or it could be another separate issue, I don't know. Usually it goes like this: I click on icon in the tray, and It looks like the menu starts blinking very rapidly, pretty much locking any other mouse input, heavily loading the CPU. But I think it either resolves itself or let's you open the task manager, I don't remember.

**Comment by bbkiwi** [comment]
Had a look and can find no log file in /home/<USERNAME>/.config/

**Comment by tom-james-watson** [comment]
I have recently upgrade lots of core dependencies in the app. Hopefully this is not longer happening.

Please upgrade to v0.7.5 and if this issue is still seen then we can reopen the issue.
