### ISSUE TITLE
powerMonitor module cannot be used before app is ready

### ISSUE THREAD

**Issue by tom-james-watson** [tom-james-watson/breaktimer-app#33]
![image](https://user-images.githubusercontent.com/3852719/76095504-aa15b700-5fc4-11ea-8bcb-f94b36bbdd45.png)

**Comment by rak-sj** [comment]
I've gotten this popup ever since Break Timer was changed from a plug-in extension to an app.
It didn't seem to affect anything, just couldn't load at the time it was trying...

**Comment by tom-james-watson** [comment]
This has been fixed in version 0.7.2, which has just been released.
