### ISSUE TITLE
Change "Notify me with" depending on working hours

### ISSUE THREAD

**Issue by garlic-hub** [tom-james-watson/breaktimer-app#37]
During working hours I would like the full screen popup, however on non-working hours I would just like the simple notification. Thank you :ok_hand:

**Comment by tom-james-watson** [comment]
Thanks for the feedback!

This is a nice idea, though I don't think it's something I want to add to the app as it would add a lot of complexity both to the logic of the app and the user settings.

I will leave the issue open to let other users add their opinions. If it becomes a widely requested feature I can consider it.
