### ISSUE TITLE
excessive logging to journald on kde

### ISSUE THREAD

**Issue by robochat** [tom-james-watson/breaktimer-app#38]
The app works well but it writes huge amounts of logs. Is there a way to reduce the logging level?
I installed the app via snap and I don't find any logs under ~/.config but there are lots of logs in journald of the type:

mars 19 13:28:03  13:28:03.692 › { state: 'idle' }
mars 19 13:28:03  13:28:03.693 › {
mars 19 13:28:03    lastTick: '2020-03-19T12:28:02.693Z',
mars 19 13:28:03    breakTime: null,
mars 19 13:28:03    secondsSinceLastTick: 1,
mars 19 13:28:03    idleResetSeconds: 300,
mars 19 13:28:03    breakSeconds: 1680
mars 19 13:28:03  }

These repeat every single second.

ps. really like the app otherwise.

**Comment by tom-james-watson** [comment]
Yeah, we can definitely dial that back a lot. It was to help debug some transient bugs.

**Comment by robochat** [comment]
That's good news. Is there anything that I can do to the current version, like a commandline switch or will this require a new version?

**Comment by tom-james-watson** [comment]
It will require a new version to be published I'm afraid!

**Comment by tom-james-watson** [comment]
Released in version `0.7.3`

**Comment by robochat** [comment]
Thank you, that fixed the issue.
