### ISSUE TITLE
After 0.7.2 update - breaktimer doesn't fully cover whole screen

### ISSUE THREAD

**Issue by michaelaaustin** [tom-james-watson/breaktimer-app#39]
The app has been working perfectly until this new update. Now a break starts, the timer screen only covers one of my two monitors. Or it covers both monitors, but something is still visible, like my taskbar or windows explorer. See screenshot for example. Please fix, thank you.
![break](https://user-images.githubusercontent.com/63358735/78799515-16daf300-796f-11ea-918c-06b153a84d15.jpg)

**Comment by tom-james-watson** [comment]
Do you know what version you were running before? It's been a long time and many versions since I've changed anything that could affect that.

Can you please explain in more detail what has changed compared to before? What is the behaviour you are expecting? Due to limitations in the ways I can create windows, covering only one monitor is how it is expected to work, unless you are mirroring screens.

**Comment by michaelaaustin** [comment]
I first downloaded Breaktimer in February and had version 0.5.0.

Since I first downloaded this app, when a break would start, one monitor become a solid color and the other would have the timer screen. I wouldn't be able to see anything on my monitors except the solid color I chose and the timer (no taskbar, no windows I had open, just the timer). Based on what you're saying, perhaps it's a fluke that mine worked so well, since I have a dual monitor setup with extended screens.

The app alerted me a couple days ago there was an update. It didn't seem to be updating on it's own, and then yesterday, when there was a break, the solid color would appear on both monitors and stay that way until I forced a log off and logged back on. At one point I forced a break to start and left it for 15 minutes, and nothing changed (just the solid color and nothing else). So I uninstalled Breaktimer through by Windows 10 system settings and reinstalled it on github, which gave me the 0.7.2 update.

Now the issues began as I stated previously. I expect it to totally lock me out of my computer as before, showing nothing but the solid color and my timer, across both monitors. Now it locks out one monitor, but it's inconsistent. Sometimes it locks out both monitors and only shows the taskbar (as shown in the screenshot above). Other times, it locks out both monitors, but still shows the Windows Explorer I had open, so I can navigate to the files I was looking at.

Perhaps this is because I have a dual monitor setup. Either way, hopefully this provides you with more useful information.

**Comment by tom-james-watson** [comment]
Yeah that's good info - thanks!

I'm not sure when I will have time to investigate this but I will try and get round to it soon.

**Comment by michaelaaustin** [comment]
Thank you! I just had a break happen, and I completely forgot to add that sometimes the timer shows up on both my monitors. That's not a problem with me, and that's happened before,, but I wanted to include that in case that helps you.

**Comment by tom-james-watson** [comment]
Apparently the break window can also render behind other windows - https://github.com/tom-james-watson/breaktimer-app/issues/57#issue-648103826

**Comment by tom-james-watson** [comment]
I've updated a lot of core dependencies recently that hopefully will have fixed this.

Please upgrade to 0.7.5 and check if this still happens. If it does we can reopen the issue. Thanks!
