### ISSUE TITLE
Duplicate tray icons

### ISSUE THREAD

**Issue by peterzhang41** [tom-james-watson/breaktimer-app#4]
Very Nice app, thanks a lot. It helps me to eliminate eye-strain.

I am using the latest Deepin OS, installed the app in the snap store, found this duplicate tray icons issue when run it form launcher or terminal. right-click and close one will close all. I will try to install other releases version.

![image](https://user-images.githubusercontent.com/13487707/65286612-89c37e80-db83-11e9-874c-a0ada6306f9a.png)
 
![image](https://user-images.githubusercontent.com/13487707/65286922-a1e7cd80-db84-11e9-94cb-2e722c4e3aab.png)

![image](https://user-images.githubusercontent.com/13487707/65287175-8e893200-db85-11e9-9f1b-3ac82938b95d.png)

![image](https://user-images.githubusercontent.com/13487707/65287193-9a74f400-db85-11e9-82ea-132343b43c07.png)

**Comment by tom-james-watson** [comment]
Hello - thanks for your bug report!

Do you mind downloading the raw `.tar.gz` and running breaktimer from there to test if the bug also happens?

You should be able to do that with:

```
wget https://github.com/tom-james-watson/breaktimer-app/releases/download/v0.4.0/BreakTimer.tar.gz
tar -xzf BreakTimer.tar.gz
cd BreakTimer
./breaktimer
```

**Comment by peterzhang41** [comment]
No problem, I will test it Monday when back to office as I am using Manjaro at home

**Comment by peterzhang41** [comment]
Just tried, double tray icons are not showing anymore. Having some other issues on the screen but looks not very important. It is working

![Uploading image.png…]()

**Comment by tom-james-watson** [comment]
OK. I don't think those GL errors are anything to worry about - they are lower level than the app code.

I'll keep the issue open for a while in case you or anyone else sees this issue again. If not, will close it out in a few weeks.
