### ISSUE TITLE
Give user time to postpone break

### ISSUE THREAD

**Issue by raqua** [tom-james-watson/breaktimer-app#40]
Hi,

at the moment, when I get notification about the oncoming break and want to postpone, I have to scramble fast and hope to hit the notification precisely and in time. I would like to be notified about the break much sooner, like 1 minute in advance (ideally configurable) and then once the break really is about to start have more time to postpone before it starts, at least 20 seconds. 

Thx.

**Comment by tom-james-watson** [comment]
I would like to implement support for at least a longer countdown before breaks start, as I agree it is not quite enough time to comfortably react. However, it's very difficult to achieve this with [Electron's Notification API](https://www.electronjs.org/docs/api/notification).

On linux, notifications disappear after about 6 seconds regardless of whether they are timeout or not, for example. I had to make the notifications last for 5 seconds other they did not work/appear consistently.

I will mark this as `wontfix` for now, as I don't think I have a proper way to achieve this. Will leave it open as I would like to do this and maybe the electron APIs change in the future to allow more flexibility.

**Comment by raqua** [comment]
I have this applet that keeps list of missed notifications until I remove them. The notification will stay there. So if clicking it would still work for postponing, it would still be useful, but at the moment I have no chance to test it, because there is no time for it. 
Other than that, wouldn't it be possible to sort of implement own notification? Small screen somewhere in the corner with countdown? It does not necessarily have to be a default Linux notification. I agree, those are not that useful, I was trying to have them stay on until I click with no success.
Thx.

**Comment by tom-james-watson** [comment]
I had wanted to avoid it but maybe implementing some kind of custom popup "notification" is actually a better idea. I can try and look into it when I have some time.

**Comment by rscrane49** [comment]
Adding a +1 to this enhancement; often don't get enough time to postpone break (I speculate that substantial portion is consumed by other system activities:  currently I have my break time set for 1:30, and by the time the countdown clock appears as much as half has elapsed.

**Comment by tom-james-watson** [comment]
1.0.0 completely changes how the breaks work - you now have much more time and a more obvious interaction for snoozing breaks.
