### ISSUE TITLE
Disable Window > Close when Allow end break off

### ISSUE THREAD

**Issue by snnsnn** [tom-james-watson/breaktimer-app#42]
You can end break manually using menu bar even if allow end break is turned off. Please can you disable it when "allow end break" setting is off. Menu bar shows with Alt keypress. Sorry I can't help myself to go for it all the time.

**Comment by tom-james-watson** [comment]
Related to https://github.com/tom-james-watson/breaktimer-app/issues/9

**Comment by tom-james-watson** [comment]
Thanks for your feedback. I've rolled the suggestion into https://github.com/tom-james-watson/breaktimer-app/issues/9
