### ISSUE TITLE
Add "Extend For -> <time>" option to tray

### ISSUE THREAD

**Issue by kdvcodes** [tom-james-watson/breaktimer-app#43]
So in the tray icon menu, we can start the break now or reset the break timer period. I think it would be great if we can quickly add another 15 mins to the timer while I'm doing something important. Thanks so much for your great work!

**Comment by tom-james-watson** [comment]
Not a bad idea. This is pretty similar to https://github.com/tom-james-watson/breaktimer-app/issues/13, but extending instead of disabling.

**Comment by tom-james-watson** [comment]
In retrospect, this is basically what the snooze function is for, so I don't think I'd want to add this.
