### ISSUE TITLE
Tray icon not displaying properly on solus gnome

### ISSUE THREAD

**Issue by cantalupo555** [tom-james-watson/breaktimer-app#45]
![](https://i.imgur.com/LmRSWm0.png)
Icon in gnome 3.36 is having problems.
It is impossible to access it

**Comment by tom-james-watson** [comment]
I can't recreate this. It works fine on Ubuntu 20.04, which uses gnome 3.36.

![Screenshot from 2020-04-27 11-08-50](https://user-images.githubusercontent.com/3852719/80354923-ae00df80-8877-11ea-8557-552bec6cfc5b.png)

* What distribution are you running?
* Are you running any gnome extensions? Have you tried disabling all of your gnome extensions and seeing if it still happens?

**Comment by cantalupo555** [comment]
Distribution: Solus https://getsol.us/download/
I installed the system again and then install the breaktime, the error persisted.
I tried to use the snap package, but it has the same problem.

**Comment by tom-james-watson** [comment]
Just to check - this is Solus GNOME specifically, right?

**Comment by cantalupo555** [comment]
> Just to check - this is Solus GNOME specifically, right?

Exactly.
In version 3.34 it worked normally.

**Comment by tom-james-watson** [comment]
I've just installed solus gnome in a virtual machine and directly installed breaktimer (`sudo snap install breaktimer`).

It seems to be working without issue:

![image](https://user-images.githubusercontent.com/3852719/80490474-b2092c00-8961-11ea-92da-e7a705dd3e32.png)

I imagine it's a conflict with some other application or extension that you have installed.

**Comment by cantalupo555** [comment]
> I've just installed solus gnome in a virtual machine and directly installed breaktimer (`sudo snap install breaktimer`).
> 
> It seems to be working without issue:
> 
> ![image](https://user-images.githubusercontent.com/3852719/80490474-b2092c00-8961-11ea-92da-e7a705dd3e32.png)
> 
> I imagine it's a conflict with some other application or extension that you have installed.

Did you look which version of gnome?

**Comment by tom-james-watson** [comment]
I've just reinstalled my host OS so can't easily confirm the exact gnome version. But whatever came with the latest Solus Gnome.

Yeah it looks like an upstream bug. Will close this out for now.

**Comment by cantalupo555** [comment]
Today I come to inform you that the problem has been solved.

**Comment by cantalupo555** [comment]
![](https://i.imgur.com/CGe2t3v.png)

**Comment by tom-james-watson** [comment]
Great!
