### ISSUE TITLE
working hours bug

### ISSUE THREAD

**Issue by saeedrahmo-uk** [tom-james-watson/breaktimer-app#47]
when I enable working hour inside Working hours tab, it doesn't set the period and for every period app always shows "Outside of working hours" (Ubuntu 18.04.4, gnome 3.28.2)

**Comment by tom-james-watson** [comment]
Can you send a screenshot of how you have configured your working hours? And can you send a screenshot of the tray menu and the current time?

**Comment by saeedrahmo-uk** [comment]
I didn't know why this problem was happened, but after restarting Ubuntu it has been working properly.
I appreciate you for your excellent app and thanks for responding.
