### ISSUE TITLE
Add support for choosing per-machine install

### ISSUE THREAD

**Issue by ezhil-pandian** [tom-james-watson/breaktimer-app#49]
Hi Tom,

Thanks for the brilliant app. 

We are facing issue in installing the application as a machine based rather than user based. Could you please advise how to install it as a machine based installation.

**Comment by ezhil-pandian** [comment]
Hi Tom,

Sorry for bugging. Could you please assist me on this.

**Comment by tom-james-watson** [comment]
I assume you're talking about Windows.

It looks like we would need to play with [these settings](https://www.electron.build/configuration/nsishttps://www.electron.build/configuration/nsis) to add support for these options to the installer.
