### ISSUE TITLE
Context menu doesn't work properly on Windows

### ISSUE THREAD

**Issue by gabspeck** [tom-james-watson/breaktimer-app#50]
When I right-click the tray icon on Windows, it seems the menu blinks repeatedly many times a second instead of being rendered. Sometimes after a few seconds the menu appears, most of the time it doesn't and I have to terminate the BreakTimer process.

**Comment by tom-james-watson** [comment]
Hello. Thanks for your bug report.

What version of Windows are you running?

What happens if you left click the tray icon?

Why do you need to terminate the process? What state is the app left in - does it become completely unresponsive? Does the tray blink until you kill it? Maybe you can make a screen recording of the behaviour. Thanks.

**Comment by gabspeck** [comment]
Hi, thanks for the reply.

>What version of Windows are you running?
I'm using Windows 10 1909 (Version 10.0.18363.815)

>What happens if you left click the tray icon?
The same.

>Why do you need to terminate the process? 
Sometimes I need to because it glitches so bad that I can barely click anything because it interferes with window focus.

Here's a GIF demonstrating the bug as it is a little hard to explain. When I took this capture the bug didn't manifest as aggressively, maybe there are other contributing factors. Mostly what happened here is that the context menu failed to render despite several clicks; but if you pay close attention you'll notice a moment when the menu outline flickers on and off a few times.

![breaktimer context menu bug](https://user-images.githubusercontent.com/749488/81879514-66f63800-9561-11ea-9150-f7f541a23c9a.gif)

**Comment by gabspeck** [comment]
Here's my log file by the way, it doesn't seem to contain any relevant information though...

[log.log](https://github.com/tom-james-watson/breaktimer-app/files/4625409/log.log)

**Comment by tom-james-watson** [comment]
OK - thanks for the info.

This is unlikely to be something in my code and maybe is something going wrong with electron itself. I can try updating the app to the latest electron to see if that helps.

**Comment by tom-james-watson** [comment]
I've recently updated a lot of underlying dependencies of the app that I hope have fixed this.

I will close this out - if you still see this after updating to 0.7.5, please let me know and we can reopen.
