### ISSUE TITLE
For Full Page Popup - Also allow option to add an image of Stretch Exercises

### ISSUE THREAD

**Issue by cricrazy** [tom-james-watson/breaktimer-app#51]
For the full page popup, please give an option to add an image. 

I would like it to have an image of common quick stretch exercises. And I tend to forget those. It would be a nice feature to add an image of those common desk exercises. So I can take a little break and do some stretches. 

thank you.

**Comment by tom-james-watson** [comment]
Thanks for the feature request. I'll leave this open to see if it garners any interest from other users, but for now this is not something I plan to add. I'd like to avoid over-complicating the app - the more features, the more possible bugs and the more confusing the settings become.

**Comment by Sveciaost** [comment]
I would also be interested in something similar.  Would it be possible to allow HTML within the break message?

**Comment by tom-james-watson** [comment]
Sure, letting the break message accept HTML would be an easy way to implement this, actually.

**Comment by tom-james-watson** [comment]
Implemented in https://github.com/tom-james-watson/breaktimer-app/commit/41cec20bda70405f4a179c94501ecfb6e326fd8b. Will be available in version 0.8.0 which is being published now.

This changes the break title / message to be rendered as HTML, which lets the user put pretty much whatever they want on the break window, as long as they know a bit of HTML.

Warning - if you ever switch back to the "simple notification" for breaks then you will see a lot of garbled HTML in your notifications.
