### ISSUE TITLE
Start Break Now/Syncing versions

### ISSUE THREAD

**Issue by pfoterac** [tom-james-watson/breaktimer-app#52]
I started out by using the Chrome extension of Break Timer since that is where I found it. Then I decided to switch to the desktop version. However, there are some things that I really liked about the Chrome Extension version that don't seem to be available on the Desktop Version. The feature that I probably like most on the Chrome Version that isn't available on the desktop version is the easily-accessible "Start Break Now" option. I think it would be great if users were able to use this feature on the desktop version as well. If this isn't an option I think that at the very least users should be able to sync the chrome extension and the desktop version. Thus if you took a break using one version, the other would recognize that a break was taken and reset the timer.  Syncing the versions may also solve some other bugs such as still being able to work on a browser through the taskbar even if the desktop version is running breaktime mode.

**Comment by pfoterac** [comment]
I realized after hitting the comment button that you at least partially sync them by enabling idle reset. However, since this feature doesn't always work very well this doesn't exactly solve the issue 100%.

**Comment by tom-james-watson** [comment]
The chrome extension is discontinued - no further work will be done there I'm afraid.

Start Break Now is still an option - just click on the tray icon and it's an option:

![image](https://user-images.githubusercontent.com/3852719/82306578-88bb4900-99bf-11ea-962f-ae5ba2a2128c.png)

**Comment by tom-james-watson** [comment]
I'd recommend using only either the extension or only the desktop app - I can't see how using both would ever work to be honest! Obviously with the extension being discontinued, I suggest using the desktop app.
