### ISSUE TITLE
After resume from sleep, breaktimer *always* starts a break.

### ISSUE THREAD

**Issue by berkes** [tom-james-watson/breaktimer-app#53]
After resume from sleep, breaktimer *always* starts a break. 

1. Put computer to sleep.
2. Wait for at least a break-interval-duration (25 minutes, in my settings)
3. Awake the computer, it starts with an immediate break.

In practice this means that in the morning, or after lunch, the first thing I see when starting my computer, is a break. This is obvious unwanted behaviour.

This is on:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
I cannot find a way to export a detailed report for breaktimer, there seems to be no commandline flag or other window to show version details. Please point me at how to get such info, if required.

I presume the internal timer calculates the interval wrong, and does not take sleep into account.

**Comment by tom-james-watson** [comment]
Thanks for your bug report!

Fixed in https://github.com/tom-james-watson/breaktimer-app/commit/b83e0cfee5559bd9513d4d28bab065e4488035a9. Has just been released as version 0.8.1.
