### ISSUE TITLE
App picked up by McAfee as a virus

### ISSUE THREAD

**Issue by ChamacoArano** [tom-james-watson/breaktimer-app#56]
McAfee Multi Access has identified breaktimer as a virus. 
Detail from McAfee:
Virus name: Real Protect-EC!D01B651A936C

**Comment by tom-james-watson** [comment]
Not much we can do about this. Antivirus are notorious for false positives. Regardless, the fact that the [app is not signed](https://github.com/tom-james-watson/breaktimer-app/issues/15) means I'm not surprised this ends up happening.
