### ISSUE TITLE
Postpone not working right

### ISSUE THREAD

**Issue by MJae** [tom-james-watson/breaktimer-app#59]
When I hit postpone in the pop-up, sometimes, it adds three minutes to the break time instead of postponing the break. I cannot tell when it would happen. It happens randomly. Sometimes, the break would be postponed - as it should, per settings. Sometimes, the break will still continue, but with the three minutes added on top of the time set.

Some info that might be helpful:
- OS: Windows 10
- BreakTimer 0.7.3

**Comment by tom-james-watson** [comment]
> Sometimes, the break will still continue, but with the three minutes added on top of the time set.

What do you mean exactly? That the actual length of the break - the time that is shown on the fullscreen break window - is extended by the postpone about?

**Comment by MJae** [comment]
> ... is extended by the postpone about?

I'm not sure I understand this part, but I'm just saying that, instead of the break being postponed after clicking the pop-up, the break still happens but with extra time added. For example, the break becomes eight minutes, instead of the five minutes I set.

**Comment by MJae** [comment]
I also tried to observe the extended break on and, when the extra time elapsed, the break would restart to the normal time.

To illustrate: My setup is five minutes break, three minutes postpone. If I click postpone and it doesn't work, a break starts for eight minutes instead. After three minutes passes, it would appear that the break is over because the sound would play. What happens is that it will start a new countdown for the original five minutes.

**Comment by tom-james-watson** [comment]
I can't say I've ever seen this happen! Without being able to reproduce this there's not much I can do at this point.

**Comment by MJae** [comment]
It's still happening, though. Since it happens randomly, I can't do a capture. Try delaying your postpone attempt. I noticed that it happens more if you do not hit postpone immediately after the notification pops up.

**Comment by tom-james-watson** [comment]
Given how breaks and snoozing has been reworked in 1.0.0, I'm going to close this out. If you see something similar on the new version, feel free to open a new issue.
