### ISSUE TITLE
How do I remove all of BreakTimer from my computer? Windows 10 and up to date

### ISSUE THREAD

**Issue by bthezebra** [tom-james-watson/breaktimer-app#61]
HI, 

I have tried using the breaktimer desktop app and it worked well enough initially. However, when I wanted to change settings and disable the breaks, the changes were not happening. I decided to uninstall to remove from my computer. It still continues to populate breaks at the same times. I tried re downloading and adjusting the settings but it makes no difference. I set it to Breaks enabled to be in the off positon as well as the start up on Windows. I am still having the breaks show up, cannot seem to find the background process to force it to quit. 

I am running version 0.7.2

Someone please help me to stop the breaks!

**Comment by tom-james-watson** [comment]
Are you actually pressing "Save" after making changes to settings?

You can remove BreakTimer in the same way as you remove any other program - https://support.microsoft.com/en-us/help/4028054/windows-10-repair-or-remove-programs
