### ISSUE TITLE
[Feature Request] Synchronization between multiple machines

### ISSUE THREAD

**Issue by ompugao** [tom-james-watson/breaktimer-app#62]
When I am using multiple machines (one is windows, the other is linux, both of them have breaktimer.app) simultaneously, Breaktimer.app in each machine alerts me one another at a different timing.
I hope it could be synchronized within machines in the same LAN network.

**Comment by ompugao** [comment]
btw, thank you for your great product! I cannot work without this app.

**Comment by tom-james-watson** [comment]
That would be very difficult to get right.

I don't want to add accounts or anything like that - I think that is a huge amount of added complexity and privacy considerations for very limited benefit.

Maybe you could do something like searching for other machines on your local network and trying to communicate between them somehow. But again, there are a lot of privacy and security considerations there. And imagine doing that on a lan in a large office.

I don't think there's anything reasonable we can do here without making the app way more complicated for little added benefit.

I'd suggest just using the enable/disable feature on whatever is the secondary machine. Maybe if https://github.com/tom-james-watson/breaktimer-app/issues/13 were added that would be useful too.

**Comment by ompugao** [comment]
ok, thank you for your consideration
