### ISSUE TITLE
Break timer does not show up in all desktop 

### ISSUE THREAD

**Issue by Da-Viper** [tom-james-watson/breaktimer-app#63]
System : Linux 
DE: KDE manjaro 5.19.3 

**Scenario** 
On full sreen break time activated 

**Observed  Result ** 
Break time window appears above the current  working  virtual desktop 

**Expected result **
Break time window appears above all the working virtual desktop available

Summary : I normally work with many virtual desktop at the same time, and when breaktime activates it is only on the current working virtual desktop instead of all the virtual desktops,

**Comment by tom-james-watson** [comment]
This is expected behaviour at the moment. If I remember correctly there was no good way of doing this.

I agree it would be better if it is somehow possible.

**Comment by tom-james-watson** [comment]
With the changes to how breaks work in 1.0.0, the break window should now appear on all desktops.
