### ISSUE TITLE
[FR] Ability to set mini breaks 

### ISSUE THREAD

**Issue by Da-Viper** [tom-james-watson/breaktimer-app#64]
System : Linux 
DE: KDE manjaro 5.19.3 

basically to be able to set like small 10-20 second breaks 
and also the normal long breaks

**Comment by tom-james-watson** [comment]
That would basically be a pommadoro timer. I think at this point it's better to keep the app simple with just one type of break.

If somebody wants to come up with a full breakdown of how this would work, some mockups of the settings etc then maybe it could be considered.
