### ISSUE TITLE
BreakTimer not working

### ISSUE THREAD

**Issue by kendall-freese** [tom-james-watson/breaktimer-app#65]
My BreakTimer has not been working, it says I am "Outside of Working Hours" even though I am not.
<img width="313" alt="Screen Shot 2020-08-06 at 12 57 07 PM" src="https://user-images.githubusercontent.com/69210122/89576666-6da0ee00-d7e4-11ea-8689-0b86a3922412.png">

**Comment by tom-james-watson** [comment]
Can you show me a screenshot of the relevant part of the settings where you have configured working hours?

**Comment by kendall-freese** [comment]
Hi Tom,

Thank you for your reply. Please see screenshot here:

[image: Screen Shot 2020-08-07 at 8.32.10 AM.png]
Thank you!!
- Kendall

**Comment by tom-james-watson** [comment]
I'm afraid that's not attached properly. Maybe replying via email doesn't support attachments. Probably need to open the actual GitHub issue and paste into a comment there.

**Comment by kendall-freese** [comment]
<img width="493" alt="Screen Shot 2020-08-10 at 9 11 28 AM" src="https://user-images.githubusercontent.com/69210122/89804808-831a5e80-dae9-11ea-8a7b-acad3b094c6c.png">

**Comment by tom-james-watson** [comment]
The times are in 24 hour format. I assume by 4:00 you mean 4pm? In which case you should change the "Breaks to" to 16:00.

I guess it shouldn't be possible to put an end time that is earlier than a start time, though.

**Comment by kendall-freese** [comment]
Hi Tom,

Thanks so much, I did not realize it was a 24 hour format I appreciate your
help!
