### ISSUE TITLE
Disable Save button on no-changes

### ISSUE THREAD

**Issue by ErezT** [tom-james-watson/breaktimer-app#66]
In the settings window the **save** button is always clickable even when no changes were made.
Clicking the save button shows a toast at the bottom that settings where saved.
Clicking the save button again and again stacks them up - see screenshot below:
![break](https://user-images.githubusercontent.com/12018324/89982712-e984b580-dc7e-11ea-8cca-12bb243521b4.png)

Suggestion, make the save button enabled when changes were detected and disabled otherwise.

**Comment by tom-james-watson** [comment]
Fixed as of 1.0.0. Thanks for the suggestion!
