### ISSUE TITLE
Working hours not working on Sundays

### ISSUE THREAD

**Issue by ErezT** [tom-james-watson/breaktimer-app#67]
I have set the following settings:
**Breaks from** to 9:00
**Breaks to** to 18:00
**Breaks on** Sunday to Thursday
on Sunday (August 16th) at around 9:43 the icon shows **Outside of working hours** (see screenshot below)
Ran 'date' command a while later and the result shows:
_Sun Aug 16 09:46:24 EEST 2020_ so its within working hours
Possible issues with timezone or locale?
I guess that to reproduce this set the working hours similar to mine and change the local timezone on the device (i'm on Ubuntu 18.04.5).
![working-hours](https://user-images.githubusercontent.com/12018324/90328617-6e850d00-dfa6-11ea-9d24-43daa4887a62.png)

**Comment by tom-james-watson** [comment]
I've had another user email in saying they are having problems with working hours and it was for a sunday too. Might be an issue with sundays specifically.

Needs investigation.

**Comment by Jackrwal** [comment]
I'm also experiencing this issue, on windows, with exactly the same days and hours

**Comment by rscrane49** [comment]
Same issue. Mac OS High Sierra 10.13.6 
![About screen](https://user-images.githubusercontent.com/71162171/97808028-32bb2480-1c32-11eb-879a-897ce470e84c.png)

**Comment by Catsvilles** [comment]
Confirming issue, Ubuntu 18.04

**Comment by davidafuller01** [comment]
+1. BreakTimer 0.7.6 on macOS Big Sur 11.0.1.

**Comment by tom-james-watson** [comment]
Closed by https://github.com/tom-james-watson/breaktimer-app/pull/79. I'll release a new version (0.7.7) now.

**Comment by tom-james-watson** [comment]
Actually will do that tomorrow as I won't have access to linux till then!

**Comment by tom-james-watson** [comment]
0.7.7 is now officially released, so update to get the fix. Thanks to @idochetrit for the fix :slightly_smiling_face:
