### ISSUE TITLE
is it a spam app?

### ISSUE THREAD

**Issue by rizwanatta** [tom-james-watson/breaktimer-app#68]
I installed it on MAc late 2015 running Catalina! and this installing preferences in settings just got vanished! no UI! no nothing at all. 😡

then I had to go to an activity monitor and saw it was taking like 10% of CPU and was running in the background! which made me suspicious! 

anybody else having this problem!

**Comment by tom-james-watson** [comment]
If the app is using excess-CPU then that is potentially a bug, or maybe an update check or something particularly CPU-intensive happened to be going on when you were looking.

Other than that, closing this as a baseless, unconstructive accusation and not a real bug report / feature request.
