### ISSUE TITLE
Action with (youtube) video playing

### ISSUE THREAD

**Issue by rscrane49** [tom-james-watson/breaktimer-app#69]
If a break starts with a YT video playing, screen blanks but video keeps playing. It seems like it should pause.

**Comment by tom-james-watson** [comment]
Unfortunately there's no way for us to control other applications, so not much we can do.

**Comment by rscrane49** [comment]
Thanks for getting back to me so quickly.  Your app does exactly what I need; so happy to find it after trying out about a dozen others that are too complicated or too inflexible.  I don't use social media much at all; where can I leave you a review?

**Comment by tom-james-watson** [comment]
The only place I think reviews can be left at the moment are in the Ubuntu software centre, if you're using Ubuntu. If not, just tell your friends 🙂
