### ISSUE TITLE
Ability to set custom sounds for break start and end

### ISSUE THREAD

**Issue by snnsnn** [tom-james-watson/breaktimer-app#7]
Hi, thank you for the great app. I have been looking something to replace gnomo-pomodoro which can run on any linux distros. I was asking if you could implement ability to use custom sound for breaks and end of breaks notifications. Also ability to accept terminal commands like run, start, stop etc, would be terrific.

**Comment by tom-james-watson** [comment]
Custom sounds is not a bad idea, yeh. 

What exactly do you mean for the terminal commands though. You mean you'd like a cli version of  the app?

**Comment by tom-james-watson** [comment]
Will make this issue just be for setting custom sounds.

cli commands is now a separate issue here - https://github.com/tom-james-watson/breaktimer-app/issues/25

**Comment by tom-james-watson** [comment]
I've actually finished adding support for those cli args FYI - check https://github.com/tom-james-watson/breaktimer-app/issues/25

**Comment by Satyrars** [comment]
Custom sounds would be great!
_`By the way what's the etiquette here on GitHub for such '+1's?`_

**Comment by tom-james-watson** [comment]
You can give thumbs up to messages:

![image](https://user-images.githubusercontent.com/3852719/76940666-f6cd8c00-68fa-11ea-918c-0188cc08f6c7.png)

**Comment by jasonkena** [comment]
A workaround would be to add the your custom `wav` files to `/Applications/BreakTimer.app/Contents/Resources/app/app/renderer/sounds`, and rename the old files to something like `gong_start.wav.bak` and `gong_end.wav.bak`. Then renaming your custom files into `gong_start.wav` and `gong_end.wav`

**Comment by tom-james-watson** [comment]
Yup that should work as a workaround if you desperately want this

**Comment by simpledn** [comment]
I've tried this on Windows and it keeps the original gong sounds. Is there another directory besides the one in AppData I can try? I've got a whole nostalgia thing going so I set my sounds as an snes game pause. Awesome btw.

**Comment by tom-james-watson** [comment]
Keeping this open because some users would like to see this. If you don't care about the feature anymore @snnsnn then you can simply unsubscribe from the issue on the right hand side.

**Comment by insasquatchcountry** [comment]
```
\\ move to proper directory
$ cd /Applications/BreakTimer.app/Contents/Resources/app/app/renderer/sounds

\\ backup .wav files
$ cp gong_start.wav gong_start.wav.backup && cp gong_end.wav going_end.wav.backup

\\ download .m4a audio and convert to .wav with proper filename
$ youtube-dl -f 140 'https://www.youtube.com/watch?v=ZZ5LpwO-An4' -o - | ffmpeg -i  pipe: gong_start.wav
$ youtube-dl -f 140 'https://www.youtube.com/watch?v=ybGOT4d2Hs8 -o - | ffmpeg -i pipe: gong_end.wav
```

I used this thread to try and get some custom sounds but I found that only the gong_start.wav sound was actually used for both start and end sounds. After a little poking around in source I found that in /breaktimer-app-master/app/renderer/components/break.tsx line 307-309 there's a comment that says that they sidestepped an issue by just using the same function for both.

```
 // For some reason the end gong sometimes sounds very distorted, so just
 // reuse the start gong.
      ipcRenderer.invokeGongStartPlay();
``` 

I think the issue was actually with their audio file as when I just play it on my mac it sounds distorted. I've changed line 309 and am trying to package from source with npm but I'm running into an issue where it prints that ```/tmp/build6582765436.sh: line 2: concurrently: command not found``` At this point, I am out of my depth here. 

Any help would be appreciated.

Better yet, we could just fix gong_end.wav, maybe add the option to turn Start and End on/off individually, and push it to the main. 

¯\_(ツ)_/¯

**Comment by tom-james-watson** [comment]
lol at your choice of song

I actually like the idea of having a single audio file play out whilst the break is running

**Comment by tom-james-watson** [comment]
I don't think I'd want to add the complexity of supporting completely custom sounds, but version 1.3.0 at least has 5 differenet sounds to choose from.
