### ISSUE TITLE
I would like to occasionally know the time till next break.

### ISSUE THREAD

**Issue by qs5779** [tom-james-watson/breaktimer-app#74]
Subject says it all. Thanks.

**Comment by tom-james-watson** [comment]
![image](https://user-images.githubusercontent.com/3852719/96733600-eeba5b00-13b9-11eb-8d45-bef7851ea0a3.png)

It's in the system tray menu.

**Comment by qs5779** [comment]
I am sorry to have bothered you, but I can't count how many times I dropped that menu item down searching for some display option. I'll just chalk it up to yet another Senior moment. Thank you.

**Comment by tom-james-watson** [comment]
No problem!
