### ISSUE TITLE
gnome shell crashing when fullscreen break window created on ubuntu 20.10

### ISSUE THREAD

**Issue by KeithMcClelland** [tom-james-watson/breaktimer-app#75]
I have been using BreakTImer 0.7.5 successfully for several weeks on Ubuntu 20.04. Late yesterday I upgraded to 20.10 (Groovy Gorilla). Today I was busy working in Emacs 26.3. (I'm not sure what version of Emacs I had before 20.10.) When the break came, Emacs crashed in a manner that left a ghost image of a blank screen that had to be forced to exit. The other monitor showed the green screen counting down as usual. This happened again at the next break so I disabled timing.

**Comment by tom-james-watson** [comment]
That's strange. It sounds more likely to be some kind of OS level crash, to be honest. Are you potentially memory constrained when the window opens? I wonder if emacs is killed by OOM killer.

**Comment by KeithMcClelland** [comment]
Thanks for getting back to me, Tom.

It's certainly not memory: I have a 16 GB Galago Pro 3. Maybe 3 or 4 gig in
use.

I thought it might be because I was typing when the screen change came so I
sat back and watched it. Nope; emacs was killed anyway.

I use two monitors: the laptop and a larger external one. I pretty much
always use emacs full screen on the external one. When it happens, the
laptop screen does its green countdown thing and the external goes
nuts--but not green. Both times that it happened before I wrote to you, a
white-screen zombie stayed around. I did it again twice today with about
the same results except that the zombie did not persist. I made a video
from just before the break started until the screens settled down. (Note
that I was working in the second workspace.) The sequence on the external
monitor is quite peculiar: first the text goes away from emacs while the
frame stays. Then a composite of parts of all three workspaces showed for a
moment, and then the second workspace with gnome terminal but not emacs
sprang into view. You'll also notice that I had a shell operating in the
right-hand emacs frame but that turned out not to matter.

Whew!

Thanks,
Keith

**Comment by tom-james-watson** [comment]
Did you mean to attach a video? GitHub still can't embed videos by the way, so it's easiest to upload to https://streamable.com or something like that.

To me it sounds like the compositor bugging out. Are you using X or Wayland? I imagine X. I'm on Ubuntu 20.04 and was going to upgrade to 20.10 this weekend, so I will see if I can recreate.

As a workaround for now, I suggest going to the break timer settings and changing "Notify me with" to "simple notifiation".

**Comment by KeithMcClelland** [comment]
Thanks Tom.

I put the video on Google drive:
https://drive.google.com/file/d/1ZGjFRRt2C30v5JZvxD8YVk9ic9f2xC21/view?usp=sharing

keith@keith-Galago-Pro:~$ loginctl show-session 2 -p Type
Type=x11

I tried having focus on other apps. They don't misbehave like emacs does.

Thanks,
Keith

**Comment by tom-james-watson** [comment]
If you put something on your laptop screen (where the break was being created) and full screen it, does the same thing happen?

E.g. put a browser window there and press F11.

**Comment by KeithMcClelland** [comment]
Okay, I tried all kinds of things using full screen and big and small and
hidden behind another.

Three results:

- Only one display ever goes to the green countdown
- The green screens just popped up on both displays before 20.10. Now that
never happens: some kind of disruption occurs before the countdown screen
appears
- Emacs never survives...even if it's hidden behind something else; even if
it's in another workspace

I tried Wayland a few years ago when it first came out but not everything
worked well with it so I went back to X11 and have never considered it
again. Should I give it a try?

Thanks,
Keith

**Comment by tom-james-watson** [comment]
RE wayland - nope, I don't recommend it. It was a case of if you said you were using wayland then I'd say it's probably wayland's fault!

I'll have to give this a go when I upgrade.

**Comment by tom-james-watson** [comment]
Did you try fullscreening another app to see if it caused the same issue like I suggested?

**Comment by KeithMcClelland** [comment]
Yes, sorry I didn't say that explicitly. I was using Chrome for that. No
problem. Of course emacs doesn't actually do a full screen...it just does
as-big-as-possible.

Keith

**Comment by tom-james-watson** [comment]
Upgrade to 20.10 and it looks like gnome shell is crashing when the break window is created. I'm not doing anything particularly wild here, just creating a window and fullscreening it.

![image](https://user-images.githubusercontent.com/3852719/97859934-94968f80-1d01-11eb-9db1-4d48cbc95464.png)

**Comment by tom-james-watson** [comment]
This should be fixed in 0.7.6, which is being published now.
