### ISSUE TITLE
Feature request: Chrome OS support

### ISSUE THREAD

**Issue by RHCPNG** [tom-james-watson/breaktimer-app#78]
Hi, 

Are you planning Chrome OS support? This is missed since the extension is deprecated.

Regards,

Niels

**Comment by tom-james-watson** [comment]
I'm afraid electron apps can't be built for Chrome OS, so I'm afraid not.

Google has also deprecated the idea of "Chrome Apps" and are getting devs to migrate to regular browser page applications. So basically this would mean implementing Break Timer as a web app. It's actually a reasonable idea, but it would need to be a completely separate application and is not something I personally have time to do right now.

The code is open source, so anybody who wants it is free to make it.
