### ISSUE TITLE
Autofocus end break button on break start

### ISSUE THREAD

**Issue by dpDesignz** [tom-james-watson/breaktimer-app#8]
I think it would be cool to be able to bind a key to end the break. Something like if I press enter or esc or space bar or the like, it would end the current break. 😄

**Comment by tom-james-watson** [comment]
If we autofocus the end break button, you'd be able to end the break with enter or space

**Comment by chaosdrop** [comment]
I came here to request this, and it says it's been complete, but it doesn't work this way on the macOS version. there is no simple one key way to Snooze or end the timer without touching the mouse that I've found.
