### ISSUE TITLE
Clarification for "System Events" permission on MacOS Catalina

### ISSUE THREAD

**Issue by r3a1d3a1** [tom-james-watson/breaktimer-app#82]
When opening the app for the first time, a popup asks for "System Events" permission.
When navigating to privacy section of System Preferences, it's visible under Automation section.
Skimming over the code, I only noticed one instance of using events to check if another instance of the app is open so as to navigate to settings when trying to open a new one.
Since the permission seemed quite a bit intrusive, it'd be great to clarify why it's needed before the system popup shows up.
I've not granted the permission, and the app seems to work fine, including idle detection.
Thank you.

**Comment by tom-james-watson** [comment]
This is not something the code specifically asks permission for. This isn't really like android where the app needs to specifically request permissions. I imagine that this is something within electron, e.g. for autostart or something like multiple instance protection that is triggering this.

Sorry I can't give you a more specific answer - I'm not sure, basically!

**Comment by r3a1d3a1** [comment]
No worries. Switched over to Stretchly which does an overall better job.

**Comment by dinhanhthi** [comment]
I don't allow either.
