### ISSUE TITLE
Simple notification is not persistent

### ISSUE THREAD

**Issue by Cromemco** [tom-james-watson/breaktimer-app#83]
The simple notification option only shows a notification for a few seconds then disappears. If you miss it, you'll never know. That notification should be persistent for a longer period, preferably until it's dismissed.

MacOS
Breaktimer 0.7.7

**Comment by tom-james-watson** [comment]
I decided that it didn't make sense to have the break notification be persistent. If you see it as a user 20 minutes later, it's not really of much use. On some operating systems, if you don't clear the notification then they will keep accumulating until your notification tray is full of now-useless break notifications. IMO, if a notification does not require interaction then it should not be persistent.
