### ISSUE TITLE
Flatpak and RPM Spec question

### ISSUE THREAD

**Issue by jubalh** [tom-james-watson/breaktimer-app#85]
Could we have a flatpak for this? :)
Also is there somewhere the rpm spec file available?

**Comment by tom-james-watson** [comment]
The different builds come from https://www.electron.build. To have support for flatpak, support would need to be added there. So not any time soon, unfortunately.

> Also is there somewhere the rpm spec file available?

I'm not sure what this means - as everything is handled by electron-builder, I don't really have to do anything special to build the rpm.
