### ISSUE TITLE
Top bar indicator not present in Ubuntu 20.04

### ISSUE THREAD

**Issue by amtseng** [tom-james-watson/breaktimer-app#87]
I recently updated my OS from Ubuntu 18.04 to 20.04, and the icon for BreakTimer has unfortunately disappeared in the top bar. Without that icon, I can no longer do things like temporarily disable BreakTimer, or check how much time I have until the next break period.
![image](https://user-images.githubusercontent.com/5652408/105769001-069dff80-5f12-11eb-9696-3945b792e397.png)

I've reinstalled BreakTimer from the .deb file but to no avail. Any tips on getting this icon back? Thanks!

**Comment by tom-james-watson** [comment]
Is the app definitely running? Try launching it again from the app launcher.

**Comment by amtseng** [comment]
Yep, the app is definitely running! The basic function of notifying breaks and showing that big teal screen still works as normal. This issue also persists between machine/app restarts.

**Comment by tom-james-watson** [comment]
OK. Do you have other apps that show app indicators? Do they show without issue? I think the "en" indicator there is an app indicator so I assume the app indicator extension is still working.

**Comment by amtseng** [comment]
Hm, that's a great question. The "en" indicator is a language toggle. I think it's a system program rather than a third-party app.
Sorry, do you happen to have any tips on verifying that the app indicator extension is working (or pointing me to a resource for that)? Thanks!

**Comment by tom-james-watson** [comment]
Sure, just running any application that has one, basically. Some that have an app indicator off the top of my head:

Slack
Steam
qBittorrent

qBittorrent is the easiest to install, if you don't have any of those - `sudo apt install qbittorrent`.

**Comment by amtseng** [comment]
I installed Slack and qBittorrent, and I didn't get any app indicator on the top bar. I already have Steam installed and that doesn't show an indicator, either (and to my knowledge never has). So it seems like the app indicator extension is problematic here. Thank you for your assistance in debugging! If you know of any quick fixes/diagnostics for the app indicator extension, I'd really appreciate it. Thanks a lot!!

**Comment by tom-james-watson** [comment]
OK - looks like that's the problem then!

You should be able to see if the extension has any errors in the "Extensions" app which I believe is installed by default on 20.04.

You can raise a bug report at the extension here - https://github.com/ubuntu/gnome-shell-extension-appindicator.

Will close this out as there's not much we can do here. Good luck!

**Comment by amtseng** [comment]
Thanks for your help! For future reference, here are a few steps that might fix app indicator extension issues:

- Remove and reinstall `gnome-shell-extension-appindicator` (through `apt`)
- Enable the extension by running `gnome-extensions enable ubuntu-appindicators@ubuntu.com`

The latter step in particular worked for me!
