### ISSUE TITLE
How to start the timer in Windows

### ISSUE THREAD

**Issue by ALRuth** [tom-james-watson/breaktimer-app#89]
I initially downloaded the extension in Chrome, and the timer started immediately. Later I decided to remove the extension and download the desktop version for Windows, It was easy to customize, but I can't figure out how to start the timer. Am I overlooking something obvious?

**Comment by tom-james-watson** [comment]
The app runs in the background. You can access it via the breaktimer icon in the system tray. You can configure the settings for the app from there. Probably you are outside of the default working hours.

**Comment by ALRuth** [comment]
Yes, it started automatically after I sent the message...I love it! Is there a way to see how long it is until the next break? I didn't see it in the Windows system tray...
    On Tuesday, February 16, 2021, 04:27:47 AM CST, Tom Watson <notifications@github.com> wrote:  
 
 


The app runs in the background. You can access it via the breaktimer icon in the system tray. You can configure the settings for the app from there. Probably you are outside of the default working hours.

**Comment by ALRuth** [comment]
Got it figured out! Thanks so much!!
    On Tuesday, February 16, 2021, 04:27:47 AM CST, Tom Watson <notifications@github.com> wrote:  
 
 


The app runs in the background. You can access it via the breaktimer icon in the system tray. You can configure the settings for the app from there. Probably you are outside of the default working hours.
