### ISSUE TITLE
Add a confirmation to closing break window when end break disabled

### ISSUE THREAD

**Issue by tom-james-watson** [tom-james-watson/breaktimer-app#9]
I don't think we should completely remove the ability to end a break, as that basically locks the machine up for the length of the break.

You can still close a break window with `ctrl/cmd+w` even if end break is disabled, which I think is the right decision, however in this case I think a confirmation window that makes you feel bad should popup. Something like - "You asked to disallow ending breaks early - are you sure you want to close the window?".

**Comment by tom-james-watson** [comment]
As suggested in https://github.com/tom-james-watson/breaktimer-app/issues/42, this should happen regardless of the way you close the window, such as closing it from the menu bar.

**Comment by dwwarne** [comment]
Just starting using the app, well for my 12 year old. He quickly worked out Alt-Tab escapes from the Break Window. Can this be avoided?

**Comment by tom-james-watson** [comment]
I'm not sure - I think it should be possible. That can be looked into as part of this work.

**Comment by tom-james-watson** [comment]
No longer relevant as of the changes in 1.0.0
