### ISSUE TITLE
Scheduled breaks for specific times

### ISSUE THREAD

**Issue by Justinzobel** [tom-james-watson/breaktimer-app#92]
It would be nice to have one in the middle where we can set the time and be away from the device for that time.

**Comment by Justinzobel** [comment]
PS Keep up the good work, this is just the app I needed.

**Comment by tom-james-watson** [comment]
I think this would make sense to change to being a more generic enhancement request for having scheduled breaks at specified times. Updated title.

**Comment by Justinzobel** [comment]
Sounds good to me.
