### ISSUE TITLE
Return focus to the last focused app

### ISSUE THREAD

**Issue by indignant** [tom-james-watson/breaktimer-app#95]
Hello! I hope you're doing well and I appreciate this well made app.

I installed Break Timer to help alleviate some issues with RSI and at the same time (and for the same reason) have been trying to use my keyboard more often, rather than depending so much on my mouse.

I've noticed that with the OSX (Catalina) that the app takes focus when advocating for a break, but doesn't return focus to the last application I was using before the break.

I'm not sure if this is possible or to what degree it would work, but I think it's be beneficial to return focus to the last focused application before the break is triggered.

Thanks!

**Comment by tom-james-watson** [comment]
I don't think this is something we can control, unfortunately. What app gets focus is down to the operating system. An app can request focus, but I don't think it's possible to request for another app to receive focus (without running as root or something).
